import { useEffect,useRef,useState } from 'react';
import { Smartphone,X } from 'lucide-react';
import { createRemoteSession,getRemoteState,publishRemoteState,type RemoteCommand,type RemoteSession } from './remoteApi';
const keyFor=(command:RemoteCommand)=>({up:'ArrowUp',down:'ArrowDown',left:'ArrowLeft',right:'ArrowRight',ok:'Enter',back:'Escape'} as Partial<Record<RemoteCommand,string>>)[command];
const dispatchKey=(key:string)=>document.dispatchEvent(new KeyboardEvent('keydown',{key,bubbles:true,cancelable:true}));
const activeVideo=()=>document.querySelector<HTMLVideoElement>('.projector-shell video');
const setSleep=(until:number)=>{if(until)localStorage.setItem('onyx-sleep-until',String(until));else localStorage.removeItem('onyx-sleep-until');window.dispatchEvent(new CustomEvent('onyx-sleep-timer-change',{detail:until}))};
const wake=()=>{const button=document.querySelector<HTMLButtonElement>('.sleep-wake');if(button){button.click();return}const scene=document.querySelector<HTMLElement>('.sleep-scene');if(scene){scene.click();window.setTimeout(()=>document.querySelector<HTMLButtonElement>('.sleep-wake')?.click(),40)}};
export function ProjectorRemoteBridge(){const[session,setSession]=useState<RemoteSession|null>(null);const[paired,setPaired]=useState(false);const[showPairing,setShowPairing]=useState(false);const lastSequence=useRef(0);
 useEffect(()=>{let disposed=false;void createRemoteSession().then(value=>{if(!disposed)setSession(value)}).catch(()=>{});return()=>{disposed=true}},[]);
 useEffect(()=>{if(!session)return;const apply=(command:RemoteCommand)=>{const key=keyFor(command);if(key){dispatchKey(key);return}const video=activeVideo();if(command==='playPause'&&video){video.paused?void video.play():video.pause()}else if(command==='seekBack'&&video)video.currentTime=Math.max(0,video.currentTime-10);else if(command==='seekForward'&&video)video.currentTime=Math.min(Number.isFinite(video.duration)?video.duration:video.currentTime+10,video.currentTime+10);else if(command==='volumeUp'&&video)video.volume=Math.min(1,video.volume+.1);else if(command==='volumeDown'&&video)video.volume=Math.max(0,video.volume-.1);else if(command.startsWith('sleep')){const map:{[key:string]:number}={sleepNow:Date.now(),sleep30:Date.now()+30*60_000,sleep60:Date.now()+60*60_000,sleep120:Date.now()+120*60_000};setSleep(map[command])}else if(command==='wake')wake()};
 const poll=window.setInterval(()=>void getRemoteState(session.token).then(state=>{setPaired(state.controllerCount>0);if(state.sequence>lastSequence.current&&state.command){lastSequence.current=state.sequence;apply(state.command)}}).catch(()=>{}),350);
 const publish=window.setInterval(()=>{const video=activeVideo();const title=document.querySelector<HTMLElement>('.live-player-info h2')?.innerText||document.querySelector<HTMLElement>('.player-page h1')?.innerText||'Onyx';const subtitle=document.querySelector<HTMLElement>('.live-player-info span:not(.live-badge)')?.innerText;const artwork=document.querySelector<HTMLImageElement>('.projector-channel.tuned img')?.src;void publishRemoteState(session.token,{projectorConnected:true,nowPlaying:{title,subtitle,artwork,paused:video?.paused,currentTime:video?.currentTime,duration:Number.isFinite(video?.duration)?video?.duration:undefined,volume:video?.volume,live:Boolean(document.querySelector('.projector-live-page'))},sleepUntil:Number(localStorage.getItem('onyx-sleep-until'))||0,sleeping:document.body.classList.contains('sleep-mode')}).catch(()=>{})},1000);
 return()=>{clearInterval(poll);clearInterval(publish)}},[session]);
 if(!session)return null;const remoteUrl=`${location.origin}${session.remoteUrl}`;return <><button className={`projector-remote-trigger ${paired?'paired':''}`} type="button" onClick={()=>setShowPairing(true)} aria-label="Show phone remote pairing"><Smartphone size={17}/><span>{paired?'Remote':'Remote'}</span><small>{paired?'Connected':'Pair'}</small></button>{showPairing&&<div className="projector-remote-backdrop" onClick={()=>setShowPairing(false)}><aside className="projector-remote-pair" onClick={event=>event.stopPropagation()}><button className="projector-remote-close" type="button" onClick={()=>setShowPairing(false)} aria-label="Close phone remote pairing"><X size={22}/></button><div className="projector-remote-heading"><Smartphone size={26}/><div><strong>{paired?'Phone remote connected':'Scan to control'}</strong><span>{paired?'Scan again to connect another phone':'Open the camera on your phone and scan this code'}</span></div></div><img className="projector-remote-qr" src={`https://api.qrserver.com/v1/create-qr-code/?size=420x420&data=${encodeURIComponent(remoteUrl)}`} alt="QR code to open Onyx phone remote"/><div className="projector-remote-code"><span>Pairing code</span><strong>{session.code}</strong></div></aside></div>}</>}
