import { useEffect,useMemo,useState } from 'react';
import { ArrowDown,ArrowLeft,ArrowRight,ArrowUp,ChevronLeft,Pause,Play,RotateCcw,RotateCw,Volume1,Volume2,Moon,Sunrise,Search,Clapperboard,Tv,Film,Radio } from 'lucide-react';
import { getRemoteLibrary,getRemoteState,remoteArtworkUrl,sendRemoteCommand,type RemoteCommand,type RemoteMediaItem,type RemoteState } from './remoteApi';
const tokenFromPath=()=>decodeURIComponent(location.pathname.match(/^\/remote\/([^/]+)/)?.[1]??'');
const time=(seconds=0)=>`${Math.floor(seconds/60)}:${String(Math.floor(seconds%60)).padStart(2,'0')}`;
export function isPhoneRemoteRoute(){return Boolean(tokenFromPath())}
type Tab='remote'|'home'|'movies'|'tv'|'specials';
const artwork=(item:RemoteMediaItem)=>remoteArtworkUrl(item.posterUrl||item.thumbnailUrl||item.backdropUrl);
export function RemotePage(){const token=tokenFromPath();const[state,setState]=useState<RemoteState|null>(null);const[library,setLibrary]=useState<RemoteMediaItem[]>([]);const[error,setError]=useState('');const[busy,setBusy]=useState(false);const[tab,setTab]=useState<Tab>('remote');const[query,setQuery]=useState('');const[selectedShow,setSelectedShow]=useState('');
 const refresh=async()=>{try{setState(await getRemoteState(token));setError('')}catch(c){setError(String(c))}};
 useEffect(()=>{void refresh();const timer=window.setInterval(()=>void refresh(),900);return()=>clearInterval(timer)},[token]);
 useEffect(()=>{void getRemoteLibrary().then(setLibrary).catch(c=>setError(String(c)))},[]);
 const command=async(value:RemoteCommand)=>{if(busy)return;setBusy(true);try{setState(await sendRemoteCommand(token,value));setError('')}catch(c){setError(String(c))}finally{setBusy(false)}};
 const play=(id:string)=>void command(`play:${id}`);
 const playing=state?.nowPlaying;const pct=playing?.duration?Math.min(100,(playing.currentTime??0)/playing.duration*100):0;
 const movies=useMemo(()=>library.filter(item=>item.kind==='movie'),[library]);const episodes=useMemo(()=>library.filter(item=>item.kind==='episode'),[library]);const specials=useMemo(()=>library.filter(item=>item.kind==='special'),[library]);
 const shows=useMemo(()=>{const map=new Map<string,RemoteMediaItem>();episodes.forEach(item=>{const name=item.showTitle||item.title;if(!map.has(name))map.set(name,item)});return [...map.entries()].map(([title,item])=>({title,item,count:episodes.filter(ep=>(ep.showTitle||ep.title)===title).length}))},[episodes]);
 const continueItems=useMemo(()=>library.filter(item=>item.progressSeconds>0&&(!item.durationSeconds||item.progressSeconds<item.durationSeconds*.9)).sort((a,b)=>b.progressSeconds-a.progressSeconds).slice(0,20),[library]);
 const recent=useMemo(()=>library.slice().sort((a,b)=>(b.year||0)-(a.year||0)).slice(0,20),[library]);
 const matches=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return[];return library.filter(item=>`${item.title} ${item.showTitle||''} ${item.year||''}`.toLowerCase().includes(q)).slice(0,60)},[library,query]);
 const cards=(items:RemoteMediaItem[])=><div className="remote-library-grid">{items.map(item=><button className="remote-media-card" key={item.id} onClick={()=>play(item.id)}>{artwork(item)?<img src={artwork(item)} alt=""/>:<span className="remote-media-placeholder"><Film/></span>}<strong>{item.kind==='episode'&&item.showTitle?item.showTitle:item.title}</strong>{item.kind==='episode'&&<small>{item.season!=null&&item.episode!=null?`S${item.season} E${item.episode} · `:''}{item.title}</small>}{item.kind!=='episode'&&item.year&&<small>{item.year}</small>}{item.progressSeconds>0&&item.durationSeconds&&<i><b style={{width:`${Math.min(100,item.progressSeconds/item.durationSeconds*100)}%`}}/></i>}</button>)}</div>;
 const libraryView=<section className="remote-library"><div className="remote-search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search Onyx"/></div>{query? <><h2>Search results</h2>{cards(matches)}</>:tab==='home'?<><h2>Continue Watching</h2>{continueItems.length?cards(continueItems):<p className="remote-library-empty">Nothing in progress.</p>}<h2>Recently Added</h2>{cards(recent)}</>:tab==='movies'?<><h2>Movies <small>{movies.length}</small></h2>{cards(movies)}</>:tab==='specials'?<><h2>Specials <small>{specials.length}</small></h2>{cards(specials)}</>:tab==='tv'&&!selectedShow?<><h2>TV Shows <small>{shows.length}</small></h2><div className="remote-library-grid">{shows.map(show=><button className="remote-media-card" key={show.title} onClick={()=>setSelectedShow(show.title)}>{artwork(show.item)?<img src={artwork(show.item)} alt=""/>:<span className="remote-media-placeholder"><Tv/></span>}<strong>{show.title}</strong><small>{show.count} episodes</small></button>)}</div></>:<><button className="remote-library-back" onClick={()=>setSelectedShow('')}><ChevronLeft/>All shows</button><h2>{selectedShow}</h2>{cards(episodes.filter(item=>(item.showTitle||item.title)===selectedShow).sort((a,b)=>(a.season||0)-(b.season||0)||(a.episode||0)-(b.episode||0)))}</>}</section>;
 return <main className="phone-remote"><header><span className="remote-brand">ONYX</span><span className={`remote-status ${state?.projectorConnected?'online':''}`}>{state?.projectorConnected?'Projector connected':'Waiting for projector'}</span></header>{error&&<div className="remote-error">{error}</div>}
 {tab==='remote'?<><section className="remote-now"><p>NOW PLAYING</p>{playing?.artwork&&<img src={playing.artwork} alt=""/>}<div><h1>{playing?.title??'Nothing playing'}</h1>{playing?.subtitle&&<h2>{playing.subtitle}</h2>}{playing?.duration&&<><div className="remote-progress"><i style={{width:`${pct}%`}}/></div><small>{time(playing.currentTime)} / {time(playing.duration)}</small></>}</div></section><section className="remote-transport"><button onClick={()=>void command('seekBack')}><RotateCcw/><span>10</span></button><button className="remote-play" onClick={()=>void command('playPause')}>{playing?.paused?<Play/>:<Pause/>}</button><button onClick={()=>void command('seekForward')}><RotateCw/><span>10</span></button></section><section className="remote-pad" aria-label="Navigation"><button className="up" onClick={()=>void command('up')}><ArrowUp/></button><button className="left" onClick={()=>void command('left')}><ArrowLeft/></button><button className="ok" onClick={()=>void command('ok')}>OK</button><button className="right" onClick={()=>void command('right')}><ArrowRight/></button><button className="down" onClick={()=>void command('down')}><ArrowDown/></button></section><button className="remote-back" onClick={()=>void command('back')}><ChevronLeft/> Back</button><section className="remote-volume"><h3>Volume</h3><div><button onClick={()=>void command('volumeDown')}><Volume1/>−</button><button onClick={()=>void command('volumeUp')}><Volume2/>+</button></div></section><section className="remote-sleep"><h3>Sleep Timer</h3><div><button onClick={()=>void command('sleepNow')}><Moon/>Now</button><button onClick={()=>void command('sleep30')}>30m</button><button onClick={()=>void command('sleep60')}>1h</button><button onClick={()=>void command('sleep120')}>2h</button>{state?.sleeping&&<button onClick={()=>void command('wake')}><Sunrise/>Wake</button>}</div></section></>:libraryView}
 <nav className="remote-tabs"><button className={tab==='remote'?'active':''} onClick={()=>setTab('remote')}><Radio/><span>Remote</span></button><button className={tab==='home'?'active':''} onClick={()=>{setTab('home');setSelectedShow('')}}><Clapperboard/><span>Browse</span></button><button className={tab==='movies'?'active':''} onClick={()=>{setTab('movies');setSelectedShow('')}}><Film/><span>Movies</span></button><button className={tab==='tv'?'active':''} onClick={()=>{setTab('tv');setSelectedShow('')}}><Tv/><span>TV</span></button><button className={tab==='specials'?'active':''} onClick={()=>{setTab('specials');setSelectedShow('')}}><Clapperboard/><span>Specials</span></button></nav></main>}
