export type RemoteCommand = 'up'|'down'|'left'|'right'|'ok'|'back'|'playPause'|'seekBack'|'seekForward'|'volumeUp'|'volumeDown'|'sleepNow'|'sleep30'|'sleep60'|'sleep120'|'wake';
export type RemoteSession = { token:string; code:string; remoteUrl:string; expiresAt:number };
export type RemoteState = { projectorConnected:boolean; controllerCount:number; sequence:number; command?:RemoteCommand; nowPlaying?:{title:string;subtitle?:string;artwork?:string;paused?:boolean;currentTime?:number;duration?:number;volume?:number;live?:boolean}; sleepUntil?:number; sleeping?:boolean };
const remoteBase=()=>`${location.protocol}//${location.hostname}:8767`;
const request=(path:string,init?:RequestInit)=>fetch(`${remoteBase()}${path}`,{...init,headers:{...((init?.headers as Record<string,string>|undefined)??{})}});
const parse=async<T>(response:Response,message:string):Promise<T>=>{if(!response.ok)throw new Error((await response.text().catch(()=>''))||message);return response.json() as Promise<T>};
export const createRemoteSession=()=>parse<RemoteSession>(request('/api/remote/session',{method:'POST'}),'Could not create remote session.');
export const getRemoteState=(token:string)=>parse<RemoteState>(request(`/api/remote/${encodeURIComponent(token)}/state`),'Remote session unavailable.');
export const sendRemoteCommand=(token:string,command:RemoteCommand)=>parse<RemoteState>(request(`/api/remote/${encodeURIComponent(token)}/command`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({command})}),'Remote command failed.');
export const publishRemoteState=(token:string,state:Partial<RemoteState>)=>parse<RemoteState>(request(`/api/remote/${encodeURIComponent(token)}/state`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(state)}),'Could not update remote state.');
