import { BarChart3, Film, FolderOpen, History, Home, ListVideo, Lock, Music2, Play, Radio, Settings, Tv } from 'lucide-react';
import type { ReactNode } from 'react';
import type { MediaItem } from '../../types';
import { SleepTimer } from '../SleepTimer';

export type NavigationSection = 'home' | 'movies' | 'tv' | 'specials' | 'collection' | 'live' | 'music' | 'history' | 'playlists' | 'analytics' | 'settings' | 'hidden';
export type SidebarCollection = { id: string; name: string; protected: boolean };

export function Sidebar({ section, collections, selectedCollectionId, pausedMedia, onNavigate, onOpenCollection, onToggleCollectionLock, onClearHistory, onResume }: { section: NavigationSection; collections: SidebarCollection[]; selectedCollectionId: string | null; pausedMedia: MediaItem | null; onNavigate: (section: NavigationSection) => void; onOpenCollection: (id: string) => void; onToggleCollectionLock: (source: SidebarCollection) => void | Promise<void>; onClearHistory: () => void | Promise<void>; onResume: () => void }) {
  const item = (target: NavigationSection, icon: ReactNode, label: string) => <button className={section === target ? 'active' : ''} onClick={() => onNavigate(target)}>{icon}{label}</button>;
  return <aside className="sidebar">{item('home', <Home size={19} />, 'Home')}{item('movies', <Film size={19} />, 'Movies')}{item('tv', <Tv size={19} />, 'TV')}{item('specials', <FolderOpen size={19} />, 'Specials')}{collections.map(source => <button key={source.id} className={section === 'collection' && selectedCollectionId === source.id ? 'active' : ''} onClick={() => onOpenCollection(source.id)} onContextMenu={event => { event.preventDefault(); void onToggleCollectionLock(source); }} title={source.protected ? 'Right-click to lock or unlock' : undefined}>{source.protected ? <Lock size={19} /> : <FolderOpen size={19} />}{source.name}</button>)}{item('live', <Radio size={19} />, 'Live TV')}{item('music', <Music2 size={19} />, 'Music')}<button className={section === 'history' ? 'active' : ''} onClick={() => onNavigate('history')} onContextMenu={event => { event.preventDefault(); void onClearHistory(); }} title="Right-click to clear history"><History size={19} />History</button>{item('playlists', <ListVideo size={19} />, 'Playlists')}{item('analytics', <BarChart3 size={19} />, 'Analytics')}<div className="sidebar-spacer" />{pausedMedia && <button className="sidebar-resume" onClick={onResume} title={`Resume ${pausedMedia.title}`}><Play size={16} fill="currentColor" /><span><small>Resume</small>{pausedMedia.kind === 'episode' ? pausedMedia.showTitle ?? pausedMedia.title : pausedMedia.title}</span></button>}<SleepTimer />{item('settings', <Settings size={19} />, 'Settings')}</aside>;
}
