import { ChevronDown, EyeOff, LogOut, Search } from 'lucide-react';
import type { MediaItem, ServerStatus, UserProfile } from '../../types';
import type { UserAvatar } from '../../userFeaturesApi';
import { AvatarBadge } from '../UserAvatarPicker';

export function TopBar({ selected, section, query, status, activeUser, activeUserId, users, avatars, profileMenu, isDesktop, onHome, onQuery, onToggleProfiles, onSwitchUser, onOpenHidden, onSignOut }: { selected: MediaItem | null; section: string; query: string; status: ServerStatus; activeUser?: UserProfile; activeUserId: string; users: UserProfile[]; avatars: Record<string, UserAvatar>; profileMenu: boolean; isDesktop: boolean; onHome: () => void; onQuery: (value: string) => void; onToggleProfiles: () => void; onSwitchUser: (id: string) => void | Promise<void>; onOpenHidden: () => void | Promise<void>; onSignOut: () => void | Promise<void> }) {
  const hideSearch = section === 'music' || section === 'live' || section === 'settings';
  return <header className="topbar"><button className="brand brand-button" onClick={onHome}><span className="brand-mark">O</span><span>Onyx</span></button>{selected ? <div className="now-playing-title">{selected.kind === 'episode' ? selected.showTitle : selected.title}</div> : hideSearch ? <div /> : <div className="search"><Search size={18} /><input value={query} onChange={event => onQuery(event.target.value)} placeholder="Search Onyx" /></div>}<div className="topbar-right"><button className={`server-logo-status ${status.running ? 'online' : ''}`} title={`${status.running ? 'Connected' : 'Disconnected'} · ${status.localUrl}\nClick to copy`} aria-label={`${status.running ? 'Connected to' : 'Disconnected from'} ${status.localUrl}. Click to copy.`} onClick={() => void navigator.clipboard.writeText(status.localUrl)}><img src="/app-icon.png" alt="" /></button><div className="profile-wrap"><button className="profile-button" onClick={event => { event.stopPropagation(); onToggleProfiles(); }}>{activeUser?.name ?? 'User'}<ChevronDown size={14} /></button>{profileMenu && <div className="profile-menu" onClick={event => event.stopPropagation()}><div className="profile-label">Profiles</div>{users.map(user => <button key={user.id} className={user.id === activeUserId ? 'active' : ''} onClick={() => void onSwitchUser(user.id)}><AvatarBadge avatar={avatars[user.id]} name={user.name} size="sm" />{user.name}{user.isAdmin && <small>Owner</small>}</button>)}<div className="context-separator" /><button onClick={() => void onOpenHidden()}><EyeOff size={15} />Hidden media</button>{!isDesktop && <button onClick={() => void onSignOut()}><LogOut size={15} />Sign out</button>}</div>}</div></div></header>;
}
