import type { MouseEvent as ReactMouseEvent } from 'react';
import type { MediaItem, UserProfile } from '../types';
import type { RecommendationEntry } from '../userFeaturesApi';
import { RecommendationsRail } from '../components/RecommendationsRail';
import { MediaCard } from '../components/media/MediaCard';
import { Rail } from '../components/media/Rail';
import { ShowCard, type ShowCardModel } from '../components/media/ShowCard';

type HomeDestination = 'movies' | 'tv' | 'live' | 'music';

export function HomePage({ activeUser, isDesktop, splitContinueWatching, continueItems, continueMovies, continueEpisodes, recentShows, recentMovies, onNavigate, onRecommendation, onPlay, onItemMenu, onOpenShow, onShowMenu }: { activeUser?: UserProfile; isDesktop: boolean; splitContinueWatching: boolean; continueItems: MediaItem[]; continueMovies: MediaItem[]; continueEpisodes: MediaItem[]; recentShows: ShowCardModel[]; recentMovies: MediaItem[]; onNavigate: (destination: HomeDestination) => void; onRecommendation: (entry: RecommendationEntry) => void; onPlay: (item: MediaItem) => void; onItemMenu: (event: ReactMouseEvent, item: MediaItem) => void; onOpenShow: (show: ShowCardModel) => void; onShowMenu: (event: ReactMouseEvent, show: ShowCardModel) => void }) {
  return <div className="home-page"><section className="onyx-hero"><p className="eyebrow">WELCOME BACK</p><h1>{activeUser?.name ? `${activeUser.name}'s Onyx` : 'Onyx'}</h1><p>Your movies, television and optional music—without the clutter.</p><div className="hero-links"><button onClick={() => onNavigate('movies')}>View movies</button><button onClick={() => onNavigate('tv')}>View TV shows</button><button onClick={() => onNavigate('live')}>Live TV</button><button onClick={() => onNavigate('music')}>Open music</button></div></section>{isDesktop && activeUser && <RecommendationsRail userId={activeUser.id} onOpen={onRecommendation} />}{!splitContinueWatching && continueItems.length > 0 && <Rail title="Continue Watching">{continueItems.map(item => <MediaCard key={item.id} item={item} artwork="poster" onPlay={onPlay} onMenu={onItemMenu} />)}</Rail>}{splitContinueWatching && continueMovies.length > 0 && <Rail title="Continue Watching Movies">{continueMovies.map(item => <MediaCard key={item.id} item={item} artwork="poster" onPlay={onPlay} onMenu={onItemMenu} />)}</Rail>}{splitContinueWatching && continueEpisodes.length > 0 && <Rail title="Continue Watching Shows">{continueEpisodes.map(item => <MediaCard key={item.id} item={item} artwork="thumbnail" onPlay={onPlay} onMenu={onItemMenu} />)}</Rail>}<Rail title="Recently Added Shows" actionLabel="View shows" onAction={() => onNavigate('tv')}>{recentShows.map(show => <ShowCard key={show.title} show={show} onOpen={onOpenShow} onMenu={onShowMenu} />)}</Rail><Rail title="Recently Added Movies" actionLabel="View movies" onAction={() => onNavigate('movies')}>{recentMovies.map(item => <MediaCard key={item.id} item={item} onPlay={onPlay} onMenu={onItemMenu} />)}</Rail></div>;
}
