import { ArrowLeft, Subtitles } from 'lucide-react';
import type { ReactNode, RefObject } from 'react';
import type { MediaItem } from '../types';
import { resolveMediaUrl } from '../api';
import { MetadataSummary } from '../components/media/MetadataSummary';

export function PlayerPage({ item, videoRef, sourceUrl, subtitleChoice, playableSubtitles, social, episodeLabel, onBack, onPlay, onPause, onEnded, onTimeUpdate, onSubtitleChange }: { item: MediaItem; videoRef: RefObject<HTMLVideoElement | null>; sourceUrl?: string; subtitleChoice: string; playableSubtitles: MediaItem['subtitles']; social?: ReactNode; episodeLabel: (item: MediaItem) => string; onBack: () => void; onPlay: () => void; onPause: () => void; onEnded: () => void; onTimeUpdate: () => void; onSubtitleChange: (value: string) => void }) {
  const eyebrow = item.kind === 'episode' ? item.showTitle : item.kind === 'collection' ? item.collectionSourceName : item.kind === 'special' ? 'SPECIAL' : 'MOVIE';
  return <main className="content player-content"><section className="player-page" style={item.backdropUrl ? { backgroundImage: `linear-gradient(rgba(4,6,8,.82),rgba(4,6,8,.98)),url(${resolveMediaUrl(item.backdropUrl)})` } : undefined}><div className="player-page-header"><button className="back-button" data-player-back onClick={onBack}><ArrowLeft size={18} />Back</button><div><p className="eyebrow">{eyebrow}</p><h1>{item.title}</h1><p>{item.kind === 'episode' ? episodeLabel(item) : item.year ?? ''}</p><MetadataSummary item={item} />{social}</div></div><div className="video-stage"><video ref={videoRef} controls autoPlay preload="auto" onPlay={onPlay} onPause={onPause} onEnded={onEnded} onTimeUpdate={onTimeUpdate}><source src={sourceUrl} />{playableSubtitles.map(subtitle => <track key={subtitle.url} kind="subtitles" src={resolveMediaUrl(subtitle.url)} srcLang={subtitle.language} label={subtitle.label} />)}</video></div><div className="player-toolbar"><div className="player-meta">{[item.container, item.videoCodec, item.audioCodec, item.height ? `${item.height}p` : null].filter(Boolean).join(' · ')}</div><label className="subtitle-control"><Subtitles size={18} /><span>Subtitles</span><select value={subtitleChoice} onChange={event => onSubtitleChange(event.target.value)}><option value="off">Off</option>{playableSubtitles.map((subtitle, index) => <option key={subtitle.url} value={String(index)}>{subtitle.label}{subtitle.forced ? ' · Forced' : ''}</option>)}</select></label></div></section></main>;
}
