import { useEffect, useState } from 'react';
import { Check, Film, Search, Tv, X } from 'lucide-react';
import { getActiveUserId, serverBaseUrl } from '../../api';
import type { MetadataSearchResult, UserProfile } from '../../types';
import { addWishlistItem, listWishlist, searchWishlistTmdb, setWishlistStatus, type WishlistEntry } from '../../userFeaturesApi';
import '../../wishlist.css';

const posterSrc=(url?:string)=>{if(!url)return undefined;try{const parsed=new URL(url);if(parsed.hostname==='image.tmdb.org'){const parts=parsed.pathname.split('/');const size=parts[3]||'w342';const path='/'+parts.slice(4).join('/');return `${serverBaseUrl()}/api/metadata/image/${size}/${encodeURIComponent(path)}`}}catch{}return url};

export function WishlistView({user}:{user:UserProfile}){
 const userId=getActiveUserId();const[kind,setKind]=useState<'movie'|'series'>('movie');const[query,setQuery]=useState('');const[results,setResults]=useState<MetadataSearchResult[]>([]);const[requests,setRequests]=useState<WishlistEntry[]>([]);const[household,setHousehold]=useState(user.isAdmin);const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);
 const refresh=async()=>{try{setRequests(await listWishlist(userId,household));setError(null)}catch(c){setError(String(c))}};
 useEffect(()=>{void refresh()},[userId,household]);
 const search=async()=>{if(!query.trim())return;setBusy(true);setError(null);try{setResults(await searchWishlistTmdb(kind,query.trim()))}catch(c){setError(String(c))}finally{setBusy(false)}};
 const add=async(item:MetadataSearchResult)=>{try{await addWishlistItem(userId,item);await refresh();setResults(current=>current.filter(value=>value.providerId!==item.providerId))}catch(c){setError(String(c))}};
 const status=async(entry:WishlistEntry,value:'requested'|'approved'|'declined')=>{try{await setWishlistStatus(userId,entry.id,value);await refresh()}catch(c){setError(String(c))}};
 return <div className="wishlist-page"><section className="page-heading"><p className="eyebrow">WISHLIST</p><h1>Requests</h1></section><div className="wishlist-search"><div className="wishlist-kind"><button className={kind==='movie'?'active':''} onClick={()=>setKind('movie')}><Film size={16}/>Movies</button><button className={kind==='series'?'active':''} onClick={()=>setKind('series')}><Tv size={16}/>TV shows</button></div><div className="wishlist-searchbox"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void search()}} placeholder={`Search TMDB for ${kind==='movie'?'movies':'TV shows'}`}/>{query&&<button aria-label="Clear search" onClick={()=>{setQuery('');setResults([])}}><X size={16}/></button>}</div><button className="primary" disabled={busy||!query.trim()} onClick={()=>void search()}>{busy?'Searching…':'Search'}</button></div>{error&&<div className="error-banner">{error}</div>}{results.length>0&&<section className="wishlist-results">{results.map(item=><article key={`${item.provider}:${item.providerId}`}><div className="wishlist-poster">{item.posterUrl?<img src={posterSrc(item.posterUrl)} alt=""/>:<span>{item.entityType==='movie'?<Film/>:<Tv/>}</span>}</div><div><h3>{item.title}</h3><p>{item.year??'Year unknown'} · {item.entityType==='movie'?'Movie':'TV show'}</p>{item.overview&&<small>{item.overview}</small>}<button onClick={()=>void add(item)}>Add to wishlist</button></div></article>)}</section>}<div className="wishlist-list-heading"><h2>{household?'Household requests':'My requests'}</h2>{user.isAdmin&&<button onClick={()=>setHousehold(value=>!value)}>{household?'Show mine':'Show household'}</button>}</div><section className="wishlist-grid">{requests.map(entry=><article className="wishlist-card" key={entry.id}>{entry.posterUrl?<img src={posterSrc(entry.posterUrl)} alt=""/>:<div className="wishlist-placeholder">{entry.mediaType==='movie'?<Film/>:<Tv/>}</div>}<div><span className={`wishlist-status status-${entry.status}`}>{entry.status}</span><h3>{entry.title}</h3><p>{entry.year??''}{household?` · ${entry.userName}`:''}</p>{user.isAdmin&&entry.status!=='added'&&<div className="wishlist-admin-actions"><button className={entry.status==='approved'?'active':''} onClick={()=>void status(entry,'approved')}><Check size={14}/>Approve</button><button className={entry.status==='declined'?'active danger-text':''} onClick={()=>void status(entry,'declined')}>Decline</button></div>}</div></article>)}{requests.length===0&&<div className="wishlist-empty">Nothing requested yet.</div>}</section></div>;
}
