import type { MediaItem, Playlist } from '../../types';

export type TvShow = { title: string; episodes: MediaItem[]; representative: MediaItem; seasons: number; addedAt: number };
export type MenuTarget = { type: 'item'; item: MediaItem } | { type: 'show'; show: TvShow } | { type: 'season'; showTitle: string; season: number; items: MediaItem[] } | { type: 'playlist'; playlist: Playlist };
export type ContextMenuState = { x: number; y: number; target: MenuTarget; hiddenView?: boolean } | null;

export function ContextMenu({ menu, isDesktop, playlists, selectedPlaylist, onClose, onPlay, onOpenShow, onReset, onAdd, onCreate, onFixMatch, onEditLocal, onResetLocal, onFixShowMatch, onEditLocalShow, onHideItem, onHideShow, onRemovePlaylistItem, onOpenPlaylist, onDeletePlaylist }: { menu: NonNullable<ContextMenuState>; isDesktop: boolean; playlists: Playlist[]; selectedPlaylist: Playlist | null; onClose: () => void; onPlay: (item: MediaItem) => void; onOpenShow: (show: TvShow) => void; onReset: (ids: string[]) => void; onAdd: (playlistId: string, ids: string[]) => void; onCreate: (ids: string[]) => void; onFixMatch: (item: MediaItem) => void; onEditLocal: (item: MediaItem) => void; onResetLocal: (item: MediaItem) => void; onFixShowMatch: (show: TvShow) => void; onEditLocalShow: (show: TvShow) => void; onHideItem: (item: MediaItem, hidden: boolean) => void; onHideShow: (show: TvShow, hidden: boolean) => void; onRemovePlaylistItem: (playlistId: string, mediaId: string) => void; onOpenPlaylist: (playlist: Playlist) => void; onDeletePlaylist: (playlist: Playlist) => void }) {
  const target = menu.target;
  const ids = target.type === 'item' ? [target.item.id] : target.type === 'show' ? target.show.episodes.map(item => item.id) : target.type === 'season' ? target.items.map(item => item.id) : [];
  const label = target.type === 'item' ? target.item.title : target.type === 'show' ? target.show.title : target.type === 'season' ? `Season ${target.season}` : target.playlist.name;
  const action = (fn: () => void) => () => { fn(); onClose(); };
  return <div className="context-menu" style={{ left: menu.x, top: menu.y }} onClick={event => event.stopPropagation()}><div className="context-title">{label}</div>{target.type === 'item' && <button onClick={action(() => onPlay(target.item))}>Play</button>}{target.type === 'show' && !menu.hiddenView && <button onClick={action(() => onOpenShow(target.show))}>Open show</button>}{target.type === 'playlist' && <button onClick={action(() => onOpenPlaylist(target.playlist))}>Open playlist</button>}{target.type !== 'playlist' && !menu.hiddenView && <button onClick={action(() => onReset(ids))}>Reset watch status</button>}{target.type === 'item' && !menu.hiddenView && <button onClick={action(() => onHideItem(target.item, true))}>Hide for this user</button>}{target.type === 'show' && !menu.hiddenView && <button onClick={action(() => onHideShow(target.show, true))}>Hide show for this user</button>}{target.type === 'item' && menu.hiddenView && <button onClick={action(() => onHideItem(target.item, false))}>Unhide</button>}{target.type === 'show' && menu.hiddenView && <button onClick={action(() => onHideShow(target.show, false))}>Unhide show</button>}{target.type !== 'playlist' && !menu.hiddenView && <><div className="context-separator" /><div className="context-label">Add to playlist</div>{playlists.map(playlist => <button key={playlist.id} onClick={action(() => onAdd(playlist.id, ids))}>{playlist.name}</button>)}<button onClick={action(() => onCreate(ids))}>+ New playlist…</button></>}{target.type === 'item' && selectedPlaylist?.mediaIds.includes(target.item.id) && <button onClick={action(() => onRemovePlaylistItem(selectedPlaylist.id, target.item.id))}>Remove from this playlist</button>}{isDesktop && target.type === 'item' && <><div className="context-separator" /><button onClick={action(() => onFixMatch(target.item))}>Fix Match…</button><button onClick={action(() => onEditLocal(target.item))}>Edit local identification…</button><button onClick={action(() => onResetLocal(target.item))}>Reset local identification</button></>}{isDesktop && target.type === 'show' && <><div className="context-separator" /><button onClick={action(() => onFixShowMatch(target.show))}>Fix Match…</button><button onClick={action(() => onEditLocalShow(target.show))}>Edit local show name…</button></>}{target.type === 'playlist' && <><div className="context-separator" /><button className="danger" onClick={action(() => onDeletePlaylist(target.playlist))}>Delete playlist</button></>}</div>;
}
