import { useEffect, useMemo, useState } from 'react';
import { createPortal } from 'react-dom';
import { Check, Film, LoaderCircle, Plus, Tv, X } from 'lucide-react';
import { getActiveUserId, resolveMediaUrl } from '../api';
import type { MediaItem, MetadataSearchResult } from '../types';
import { addWishlistItem, searchWishlistTmdb } from '../userFeaturesApi';

type LocalResult={key:string;kind:'movie'|'series';title:string;year?:number;image?:string;mediaId:string;providerId?:string};
const cachedMedia=():MediaItem[]=>{try{const raw=sessionStorage.getItem(`onyx-media-cache:${getActiveUserId()}`);return raw?JSON.parse(raw) as MediaItem[]:[]}catch{return[]}};
const normalize=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();

export function GlobalMediaSearch(){
 const[input,setInput]=useState<HTMLInputElement|null>(null);const[query,setQuery]=useState('');const[remote,setRemote]=useState<MetadataSearchResult[]>([]);const[loading,setLoading]=useState(false);const[requested,setRequested]=useState<Set<string>>(new Set());
 useEffect(()=>{const find=()=>{const next=document.querySelector<HTMLInputElement>('.topbar .search input');setInput(current=>current===next?current:next)};find();const timer=window.setInterval(find,400);return()=>window.clearInterval(timer)},[]);
 useEffect(()=>{if(!input)return;const update=()=>setQuery(input.value);update();input.addEventListener('input',update);return()=>input.removeEventListener('input',update)},[input]);
 const media=useMemo(()=>cachedMedia(),[query]);
 const local=useMemo<LocalResult[]>(()=>{const q=normalize(query);if(q.length<2)return[];const out:LocalResult[]=[];for(const item of media.filter(item=>item.kind==='movie'))if(normalize(`${item.title} ${item.year??''}`).includes(q))out.push({key:`m:${item.id}`,kind:'movie',title:item.title,year:item.year,image:item.posterUrl,mediaId:item.id,providerId:item.providerId});const shows=new Map<string,MediaItem>();for(const ep of media.filter(item=>item.kind==='episode')){const title=ep.showTitle?.trim();if(title&&!shows.has(title))shows.set(title,ep)}for(const[title,ep]of shows)if(normalize(title).includes(q))out.push({key:`s:${ep.id}`,kind:'series',title,image:ep.posterUrl,mediaId:ep.id,providerId:ep.providerId});return out.slice(0,8)},[media,query]);
 useEffect(()=>{const q=query.trim();if(q.length<3){setRemote([]);setLoading(false);return}let dead=false;const timer=window.setTimeout(async()=>{setLoading(true);try{const[movies,series]=await Promise.all([searchWishlistTmdb('movie',q),searchWishlistTmdb('series',q)]);if(!dead)setRemote([...movies.slice(0,5),...series.slice(0,5)])}catch{if(!dead)setRemote([])}finally{if(!dead)setLoading(false)}},450);return()=>{dead=true;window.clearTimeout(timer)}},[query]);
 const openLocal=(mediaId:string)=>{input?.blur();if(input){input.value='';input.dispatchEvent(new Event('input',{bubbles:true}))}setQuery('');window.dispatchEvent(new CustomEvent('onyx-open-library-item',{detail:{mediaId}}))};
 const localFor=(result:MetadataSearchResult)=>local.find(item=>item.kind===result.entityType&&((item.providerId&&item.providerId===result.providerId)||(normalize(item.title)===normalize(result.title)&&(!item.year||!result.year||item.year===result.year))));
 const request=async(result:MetadataSearchResult)=>{await addWishlistItem(getActiveUserId(),result);setRequested(current=>new Set(current).add(`${result.provider}:${result.providerId}`))};
 if(!input||query.trim().length<2)return null;const host=input.closest<HTMLElement>('.search');if(!host)return null;
 const panel=<div className="global-search-results"><header><span>Search</span>{loading&&<LoaderCircle className="spin" size={14}/>}<button onClick={()=>{input.value='';input.dispatchEvent(new Event('input',{bubbles:true}));input.focus()}} aria-label="Clear search"><X size={15}/></button></header>{local.length>0&&<section><h4>On your server</h4>{local.map(result=><button className="global-search-row" key={result.key} onClick={()=>openLocal(result.mediaId)}>{result.image?<img src={resolveMediaUrl(result.image)} alt=""/>:<span className="global-search-art">{result.kind==='movie'?<Film size={18}/>:<Tv size={18}/>}</span>}<div><strong>{result.title}</strong><small>{result.kind==='movie'?'Movie':'TV show'}{result.year?` · ${result.year}`:''}</small></div><Check size={16}/></button>)}</section>}{remote.length>0&&<section><h4>TMDB</h4>{remote.map(result=>{const localMatch=localFor(result);const key=`${result.provider}:${result.providerId}`,done=requested.has(key);return <div className="global-search-row" key={key}>{result.posterUrl?<img src={result.posterUrl} alt=""/>:<span className="global-search-art">{result.entityType==='movie'?<Film size={18}/>:<Tv size={18}/>}</span>}<button className="global-search-copy" onClick={()=>localMatch&&openLocal(localMatch.mediaId)} disabled={!localMatch}><strong>{result.title}</strong><small>{result.entityType==='movie'?'Movie':'TV show'}{result.year?` · ${result.year}`:''}{localMatch?' · In library':''}</small></button>{localMatch?<button className="search-open" onClick={()=>openLocal(localMatch.mediaId)}>Open</button>:<button className="search-request" disabled={done} onClick={()=>void request(result)} title={done?'Requested':'Request this media'}>{done?<Check size={16}/>:<Plus size={17}/>}</button>}</div>})}</section>}{!loading&&!local.length&&!remote.length&&<p className="global-search-empty">No matches found.</p>}</div>;
 return createPortal(panel,host);
}
