import { useEffect, useRef, useState } from 'react';
import { Check, ExternalLink, Link2, LoaderCircle, RefreshCw, Unplug } from 'lucide-react';
import { disconnectIbroadcast, getIbroadcastStatus, pollIbroadcastDeviceAuth, startIbroadcastDeviceAuth, syncIbroadcast } from '../api';
import type { IbConnectionStatus, IbDeviceCode } from '../types';

export function IbroadcastConnect({onConnected}:{onConnected?:()=>void}){
  const[status,setStatus]=useState<IbConnectionStatus|null>(null);const[device,setDevice]=useState<IbDeviceCode|null>(null);const[error,setError]=useState<string|null>(null);const[busy,setBusy]=useState(false);const timer=useRef<number|null>(null);
  const refresh=async()=>{try{setStatus(await getIbroadcastStatus())}catch(cause){setError(String(cause))}};
  useEffect(()=>{void refresh();return()=>{if(timer.current)window.clearInterval(timer.current)}},[]);
  const begin=async()=>{setBusy(true);setError(null);try{const next=await startIbroadcastDeviceAuth();setDevice(next);const poll=async()=>{try{const result=await pollIbroadcastDeviceAuth(next.deviceCode);if(result.connected){if(timer.current)window.clearInterval(timer.current);timer.current=null;setDevice(null);await syncIbroadcast();await refresh();onConnected?.();}}catch(cause){if(timer.current)window.clearInterval(timer.current);timer.current=null;setError(String(cause)}}};timer.current=window.setInterval(()=>void poll(),Math.max(2,next.interval)*1000);void poll();}catch(cause){setError(String(cause))}finally{setBusy(false)}};
  const disconnect=async()=>{if(!window.confirm('Disconnect iBroadcast from this Onyx profile?'))return;try{await disconnectIbroadcast();setDevice(null);await refresh();onConnected?.()}catch(cause){setError(String(cause))}};
  const sync=async()=>{setBusy(true);try{await syncIbroadcast();await refresh();onConnected?.()}catch(cause){setError(String(cause))}finally{setBusy(false)}};
  if(!status)return <div className="provider-card"><LoaderCircle className="spin" size={20}/> Checking iBroadcast…</div>;
  if(!status.configured)return <div className="provider-card provider-warning"><Link2 size={20}/><div><strong>Onyx needs an iBroadcast client ID</strong><p>Add the client ID under Settings → Music. You create an app from iBroadcast’s web player under Apps → developer.</p></div></div>;
  if(status.connected)return <div className="provider-card"><Check size={22}/><div className="provider-grow"><strong>iBroadcast connected</strong><p>{status.providerUser??'This profile'}{status.lastSyncAt?` · synced ${new Date(status.lastSyncAt*1000).toLocaleString()}`:''}</p></div><button onClick={()=>void sync()} disabled={busy}><RefreshCw size={16}/>Sync</button><button className="danger-text" onClick={()=>void disconnect()}><Unplug size={16}/>Disconnect</button>{error&&<p className="provider-error">{error}</p>}</div>;
  if(device)return <div className="device-auth-card"><p className="eyebrow">CONNECT IBROADCAST</p><h3>Authorize Onyx</h3><p>Open the address on a phone or computer and enter this code:</p><div className="device-code">{device.userCode}</div><a href={device.verificationUriComplete??device.verificationUri} target="_blank" rel="noreferrer"><ExternalLink size={16}/>{device.verificationUri}</a><p className="muted">Waiting for authorization…</p>{error&&<p className="provider-error">{error}</p>}</div>;
  return <div className="provider-card"><Link2 size={22}/><div className="provider-grow"><strong>Connect iBroadcast</strong><p>Music belongs to the current Onyx profile and remains separate from Movies and TV.</p></div><button className="primary" onClick={()=>void begin()} disabled={busy}>{busy?'Starting…':'Connect'}</button>{error&&<p className="provider-error">{error}</p>}</div>;
}
