import { useEffect, useState } from 'react';
import { Check, LoaderCircle, Search, Star, X } from 'lucide-react';
import { applyMetadataMatch, searchMetadata } from '../api';
import type { MediaItem, MetadataSearchResult } from '../types';

export function MetadataMatchDialog({item,onClose,onMatched}:{item:MediaItem;onClose:()=>void;onMatched:(items:MediaItem[])=>void}){
 const initial=item.kind==='episode'?(item.showTitle??item.title):item.title;
 const[query,setQuery]=useState(initial);const[results,setResults]=useState<MetadataSearchResult[]>([]);const[busy,setBusy]=useState(false);const[applying,setApplying]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);
 const search=async(value=query)=>{const clean=value.trim();if(!clean)return;setBusy(true);setError(null);try{setResults(await searchMetadata(item.id,clean))}catch(c){setError(String(c));setResults([])}finally{setBusy(false)}};
 useEffect(()=>{void search(initial)},[item.id]);
 const choose=async(result:MetadataSearchResult)=>{setApplying(result.providerId);setError(null);try{onMatched(await applyMetadataMatch(item.id,result.providerId));onClose()}catch(c){setError(String(c))}finally{setApplying(null)}};
 return <div className="match-overlay" role="dialog" aria-modal="true" aria-label="Fix metadata match" onClick={onClose}><section className="match-dialog" onClick={e=>e.stopPropagation()}><header><div><p className="eyebrow">FIX MATCH</p><h2>{item.kind==='episode'?(item.showTitle??item.title):item.title}</h2><p>Choose the real {item.kind==='episode'?'TV series':'movie'}. Manual searches use the title only; the displayed year is context, not a search filter. Your chosen match is locked through rescans.</p></div><button className="icon-action" aria-label="Close" onClick={onClose}><X size={18}/></button></header><form className="match-search" onSubmit={e=>{e.preventDefault();void search()}}><Search size={18}/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${item.kind==='episode'?'TV shows':'movies'}`}/><button type="submit" disabled={busy}>{busy?<LoaderCircle className="spin" size={17}/>:<Search size={17}/>}Search</button></form>{error&&<div className="error-banner">{error}</div>}<div className="match-results">{!busy&&results.length===0&&!error&&<div className="match-empty"><Search size={32}/><strong>No results</strong><p>Try a shorter or more recognizable title.</p></div>}{results.map(result=><article className="match-result" key={`${result.provider}:${result.providerId}`}><div className="match-poster">{result.posterUrl?<img src={result.posterUrl} alt="" loading="lazy"/>:<span>{result.title.charAt(0)}</span>}</div><div className="match-copy"><div className="match-result-heading"><h3>{result.title}</h3>{result.year&&<span>{result.year}</span>}{result.rating!=null&&<span className="match-rating"><Star size={13} fill="currentColor"/>{result.rating.toFixed(1)}</span>}</div><p>{result.overview||'No description available.'}</p><small>{result.provider.toUpperCase()} #{result.providerId}</small></div><button className="primary match-use" disabled={Boolean(applying)} onClick={()=>void choose(result)}>{applying===result.providerId?<LoaderCircle className="spin" size={17}/>:<Check size={17}/>}Use this match</button></article>)}</div><footer><span>This product uses the TMDB API but is not endorsed or certified by TMDB.</span><button onClick={onClose}>Cancel</button></footer></section></div>;
}
