import { useEffect, useMemo, useRef, useState } from 'react';
import { Disc3, ListMusic, Music2, Pause, Play, RefreshCw, Search, UserRound } from 'lucide-react';
import { getIbroadcastLibrary, getIbroadcastStatus, ibroadcastStreamUrl, syncIbroadcast } from '../api';
import type { IbAlbum, IbArtist, IbConnectionStatus, IbLibrary, IbPlaylist, IbTrack } from '../types';
import { IbroadcastConnect } from './IbroadcastConnect';

type MusicMode='artists'|'albums'|'tracks'|'playlists';
const empty:IbLibrary={tracks:[],albums:[],artists:[],playlists:[]};
const duration=(seconds:number)=>`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;

export function MusicView(){
 const[status,setStatus]=useState<IbConnectionStatus|null>(null);const[library,setLibrary]=useState<IbLibrary>(empty);const[mode,setMode]=useState<MusicMode>('artists');const[query,setQuery]=useState('');const[selectedArtist,setSelectedArtist]=useState<IbArtist|null>(null);const[selectedAlbum,setSelectedAlbum]=useState<IbAlbum|null>(null);const[selectedPlaylist,setSelectedPlaylist]=useState<IbPlaylist|null>(null);const[nowPlaying,setNowPlaying]=useState<IbTrack|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const audio=useRef<HTMLAudioElement>(null);
 const load=async(force=false)=>{setBusy(true);setError(null);try{const nextStatus=await getIbroadcastStatus();setStatus(nextStatus);if(nextStatus.connected){const next=force?await syncIbroadcast():await getIbroadcastLibrary();setLibrary(next.tracks.length||!force?next:await syncIbroadcast());}else setLibrary(empty);}catch(cause){setError(String(cause))}finally{setBusy(false)}};
 useEffect(()=>{void load()},[]);
 const normalized=query.trim().toLowerCase();
 const matchesTrack=(track:IbTrack)=>!normalized||`${track.title} ${track.artist} ${track.album}`.toLowerCase().includes(normalized);
 const tracks=useMemo(()=>library.tracks.filter(matchesTrack),[library,normalized]);
 const artists=useMemo(()=>library.artists.filter(a=>!normalized||a.name.toLowerCase().includes(normalized)||library.tracks.some(t=>t.artistId===a.id&&matchesTrack(t))),[library,normalized]);
 const albums=useMemo(()=>library.albums.filter(a=>!normalized||`${a.name} ${a.artist}`.toLowerCase().includes(normalized)||a.trackIds.some(id=>library.tracks.find(t=>t.id===id&&matchesTrack(t)))),[library,normalized]);
 const playlists=useMemo(()=>library.playlists.filter(p=>!normalized||p.name.toLowerCase().includes(normalized)||p.trackIds.some(id=>library.tracks.find(t=>t.id===id&&matchesTrack(t)))),[library,normalized]);
 const albumTracks=(album:IbAlbum)=>album.trackIds.map(id=>library.tracks.find(t=>t.id===id)).filter((v):v is IbTrack=>Boolean(v));
 const playlistTracks=(playlist:IbPlaylist)=>playlist.trackIds.map(id=>library.tracks.find(t=>t.id===id)).filter((v):v is IbTrack=>Boolean(v));
 const artistAlbums=(artist:IbArtist)=>library.albums.filter(a=>a.artistId===artist.id||a.artist===artist.name);
 const play=(track:IbTrack)=>{setNowPlaying(track);requestAnimationFrame(()=>audio.current?.play().catch(()=>{}));};
 if(status&&!status.connected)return <div className="music-page"><section className="onyx-hero music-hero"><p className="eyebrow">MUSIC</p><h1>iBroadcast</h1><p>Connect this profile to bring your personal music library into Onyx.</p></section><IbroadcastConnect onConnected={()=>void load(true)}/>{error&&<div className="error-banner">{error}</div>}</div>;
 return <div className="music-page"><section className="music-header"><div><p className="eyebrow">IBROADCAST</p><h1>Music</h1><p>{library.tracks.length} tracks · {library.albums.length} albums · {library.artists.length} artists</p></div><button onClick={()=>void load(true)} disabled={busy}><RefreshCw size={17}/>{busy?'Syncing…':'Sync library'}</button></section><div className="music-search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search artist, album, artist + album, track, or playlist"/></div><div className="music-tabs"><button className={mode==='artists'?'active':''} onClick={()=>{setMode('artists');setSelectedAlbum(null);setSelectedPlaylist(null)}}><UserRound size={17}/>Artists</button><button className={mode==='albums'?'active':''} onClick={()=>{setMode('albums');setSelectedArtist(null);setSelectedPlaylist(null)}}><Disc3 size={17}/>Albums</button><button className={mode==='tracks'?'active':''} onClick={()=>{setMode('tracks');setSelectedArtist(null);setSelectedAlbum(null);setSelectedPlaylist(null)}}><Music2 size={17}/>Tracks</button><button className={mode==='playlists'?'active':''} onClick={()=>{setMode('playlists');setSelectedArtist(null);setSelectedAlbum(null)}}><ListMusic size={17}/>Playlists</button></div>{error&&<div className="error-banner">{error}</div>}
 {selectedArtist?<section><button className="back-button" onClick={()=>setSelectedArtist(null)}>← All artists</button><h2 className="music-section-title">{selectedArtist.name}</h2><div className="music-grid">{artistAlbums(selectedArtist).map(album=><AlbumCard key={album.id} album={album} onOpen={setSelectedAlbum}/>)}</div></section>:selectedAlbum?<TrackSection title={`${selectedAlbum.artist} · ${selectedAlbum.name}`} tracks={albumTracks(selectedAlbum)} onBack={()=>setSelectedAlbum(null)} onPlay={play}/>:selectedPlaylist?<TrackSection title={selectedPlaylist.name} tracks={playlistTracks(selectedPlaylist)} onBack={()=>setSelectedPlaylist(null)} onPlay={play}/>:mode==='artists'?<div className="music-grid">{artists.map(artist=><article className="music-tile" key={artist.id} onClick={()=>setSelectedArtist(artist)}>{artist.artworkUrl?<img src={artist.artworkUrl} alt=""/>:<div className="music-art-placeholder"><UserRound size={42}/></div>}<h3>{artist.name}</h3><p>{artistAlbums(artist).length} albums</p></article>)}</div>:mode==='albums'?<div className="music-grid">{albums.map(album=><AlbumCard key={album.id} album={album} onOpen={setSelectedAlbum}/>)}</div>:mode==='playlists'?<div className="music-grid">{playlists.map(playlist=><article className="music-tile" key={playlist.id} onClick={()=>setSelectedPlaylist(playlist)}>{playlist.artworkUrl?<img src={playlist.artworkUrl} alt=""/>:<div className="music-art-placeholder"><ListMusic size={42}/></div>}<h3>{playlist.name}</h3><p>{playlist.trackIds.length} tracks</p></article>)}</div>:<TrackList tracks={tracks} onPlay={play}/>} 
 {nowPlaying&&<div className="music-player"><img src={nowPlaying.artworkUrl} alt=""/><div><strong>{nowPlaying.title}</strong><span>{nowPlaying.artist} · {nowPlaying.album}</span></div><audio key={nowPlaying.id} ref={audio} src={ibroadcastStreamUrl(nowPlaying.id)} controls autoPlay/></div>}</div>;
}
function AlbumCard({album,onOpen}:{album:IbAlbum;onOpen:(album:IbAlbum)=>void}){return <article className="music-tile" onClick={()=>onOpen(album)}>{album.artworkUrl?<img src={album.artworkUrl} alt=""/>:<div className="music-art-placeholder"><Disc3 size={42}/></div>}<h3>{album.name}</h3><p>{album.artist}{album.year?` · ${album.year}`:''}</p></article>}
function TrackSection({title,tracks,onBack,onPlay}:{title:string;tracks:IbTrack[];onBack:()=>void;onPlay:(track:IbTrack)=>void}){return <section><button className="back-button" onClick={onBack}>← Back</button><h2 className="music-section-title">{title}</h2><TrackList tracks={tracks} onPlay={onPlay}/></section>}
function TrackList({tracks,onPlay}:{tracks:IbTrack[];onPlay:(track:IbTrack)=>void}){return <div className="track-list">{tracks.map(track=><button className="track-row" key={track.id} onClick={()=>onPlay(track)}>{track.artworkUrl?<img src={track.artworkUrl} alt=""/>:<div className="track-art"><Music2 size={18}/></div>}<span className="track-title"><strong>{track.title}</strong><small>{track.artist}</small></span><span className="track-album">{track.album}</span><span className="track-duration">{duration(track.durationSeconds)}</span><Play size={17}/></button>)}</div>}
