import { useEffect, useState } from 'react';
import { Check, Database, Film, FolderOpen, Image, KeyRound, Music2, Palette, Plus, RefreshCw, Save, Server, Tags, TerminalSquare, Tv, UserRound, Users, X } from 'lucide-react';
import { autoMatchMetadata, chooseLibraryPath, clearAccessPassword, clearThumbnailCache, clearTmdbToken, createUser, deleteUser, getActiveUserId, getServerStatus, getUserPreferences, listUsers, metadataProviderStatus, renameUser, rescanLibrary, setAccessPassword, setActiveUserId, setIbroadcastClientId, setMoviePath, setTmdbToken, setTvPath, setUserTheme, testTmdb } from '../api';
import { activityEntries as loadActivityEntries, clearActivity } from '../adminTools';
import type { ActivityEntry, MetadataProviderStatus, ServerStatus, ThemeName, UserProfile } from '../types';
import { IbroadcastConnect } from './IbroadcastConnect';
import { IbroadcastLogoKit } from './IbroadcastLogoKit';
import '../activityConsole.css';

type Category='general'|'library'|'metadata'|'users'|'appearance'|'remote'|'music'|'cache'|'activity';
const themes:ThemeName[]=['onyx','midnight','ember','light'];

export function SettingsPage({onChanged}:{onChanged?:()=>void}){
 const[category,setCategory]=useState<Category>('general');const[status,setStatus]=useState<ServerStatus|null>(null);const[users,setUsers]=useState<UserProfile[]>([]);const[active,setActive]=useState(getActiveUserId());const[theme,setTheme]=useState<ThemeName>('onyx');const[clientId,setClientId]=useState('');const[error,setError]=useState<string|null>(null);const[newUserOpen,setNewUserOpen]=useState(false);const[newUserName,setNewUserName]=useState('');const[nameDrafts,setNameDrafts]=useState<Record<string,string>>({});const[providers,setProviders]=useState<MetadataProviderStatus[]>([]);const[tmdbToken,setTmdbTokenDraft]=useState('');const[metadataBusy,setMetadataBusy]=useState(false);const[metadataMessage,setMetadataMessage]=useState<string|null>(null);const[activity,setActivity]=useState<ActivityEntry[]>([]);
 const syncUsers=(next:UserProfile[])=>{setUsers(next);setNameDrafts(Object.fromEntries(next.map(user=>[user.id,user.name])))};
 const refresh=async()=>{try{const[s,u,p,m]=await Promise.all([getServerStatus(),listUsers(),getUserPreferences(),metadataProviderStatus()]);setStatus(s);syncUsers(u);setTheme(p.theme);setClientId(s.ibroadcastClientId??'');setProviders(m);setError(null)}catch(c){setError(String(c))}};
 const refreshActivity=async()=>{try{setActivity(await loadActivityEntries())}catch(c){setError(String(c))}};
 useEffect(()=>{void refresh()},[]);
 useEffect(()=>{if(category!=='activity')return;void refreshActivity();const timer=window.setInterval(()=>void refreshActivity(),1500);return()=>window.clearInterval(timer)},[category]);
 const folder=async(kind:'movie'|'tv')=>{const path=await chooseLibraryPath();if(!path)return;try{kind==='movie'?await setMoviePath(path):await setTvPath(path);await refresh();onChanged?.()}catch(c){setError(String(c))}};
 const addUser=async()=>{const name=newUserName.trim();if(!name)return;try{syncUsers(await createUser(name));setNewUserName('');setNewUserOpen(false);onChanged?.()}catch(c){setError(String(c))}};
 const saveUserName=async(user:UserProfile)=>{const name=(nameDrafts[user.id]??user.name).trim();if(!name||name===user.name)return;try{syncUsers(await renameUser(user.id,name));onChanged?.()}catch(c){setError(String(c));setNameDrafts(current=>({...current,[user.id]:user.name}))}};
 const removeUser=async(user:UserProfile)=>{if(user.isAdmin||!window.confirm(`Delete ${user.name}?`))return;try{syncUsers(await deleteUser(user.id));onChanged?.()}catch(c){setError(String(c))}};
 const chooseUser=async(id:string)=>{setActiveUserId(id);setActive(id);const p=await getUserPreferences();setTheme(p.theme);onChanged?.()};
 const chooseTheme=async(value:ThemeName)=>{try{const p=await setUserTheme(value);setTheme(p.theme);document.documentElement.dataset.theme=p.theme;onChanged?.()}catch(c){setError(String(c))}};
 const password=async()=>{try{if(status?.accessPasswordSet){if(window.confirm('Remove the browser access password?'))await clearAccessPassword();}else{const value=window.prompt('New browser access password (minimum 8 characters):');if(value)await setAccessPassword(value);}await refresh()}catch(c){setError(String(c))}};
 const saveTmdb=async()=>{const token=tmdbToken.trim();if(!token)return;setMetadataBusy(true);setMetadataMessage(null);try{await setTmdbToken(token);await testTmdb();setTmdbTokenDraft('');setMetadataMessage('TMDB connected successfully.');await refresh()}catch(c){setError(String(c))}finally{setMetadataBusy(false)}};
 const runAutoMatch=async()=>{setMetadataBusy(true);setMetadataMessage(null);try{const count=await autoMatchMetadata();setMetadataMessage(`${count} high-confidence ${count===1?'item':'items'} matched. Ambiguous media was left unchanged.`);onChanged?.()}catch(c){setError(String(c))}finally{setMetadataBusy(false)}};
 const tmdb=providers.find(p=>p.provider==='tmdb');const tvdb=providers.find(p=>p.provider==='tvdb');
 return <div className="settings-page"><aside className="settings-nav"><h2>Settings</h2><button className={category==='general'?'active':''} onClick={()=>setCategory('general')}><Server size={18}/>General</button><button className={category==='library'?'active':''} onClick={()=>setCategory('library')}><Database size={18}/>Libraries</button><button className={category==='metadata'?'active':''} onClick={()=>setCategory('metadata')}><Tags size={18}/>Metadata</button><button className={category==='users'?'active':''} onClick={()=>setCategory('users')}><Users size={18}/>Users</button><button className={category==='appearance'?'active':''} onClick={()=>setCategory('appearance')}><Palette size={18}/>Appearance</button><button className={category==='remote'?'active':''} onClick={()=>setCategory('remote')}><KeyRound size={18}/>Remote access</button><button className={category==='music'?'active':''} onClick={()=>setCategory('music')}><Music2 size={18}/>Music</button><button className={category==='cache'?'active':''} onClick={()=>setCategory('cache')}><Image size={18}/>Cache</button><button className={category==='activity'?'active':''} onClick={()=>setCategory('activity')}><TerminalSquare size={18}/>Activity</button></aside><section className="settings-content">{error&&<div className="error-banner">{error}</div>}
 {category==='general'&&<><p className="eyebrow">ONYX</p><h1>General</h1><div className="settings-card"><h3>Server</h3><p>{status?.localUrl??'Starting…'}</p><dl><div><dt>Media items</dt><dd>{status?.itemCount??0}</dd></div><div><dt>FFmpeg</dt><dd>{status?.ffmpegAvailable?'Available':'Not found'}</dd></div><div><dt>FFprobe</dt><dd>{status?.ffprobeAvailable?'Available':'Not found'}</dd></div></dl></div></>}
 {category==='library'&&<><p className="eyebrow">MEDIA</p><h1>Libraries</h1><div className="settings-card setting-row"><Film/><div><h3>Movies</h3><p>{status?.moviePath??'No folder selected'}</p></div><button onClick={()=>void folder('movie')}><FolderOpen size={17}/>Change</button></div><div className="settings-card setting-row"><Tv/><div><h3>TV Shows</h3><p>{status?.tvPath??'No folder selected'}</p></div><button onClick={()=>void folder('tv')}><FolderOpen size={17}/>Change</button></div><button onClick={async()=>{await rescanLibrary();onChanged?.()}}><RefreshCw size={17}/>Rescan libraries</button></>}
 {category==='metadata'&&<><p className="eyebrow">IDENTIFICATION</p><h1>Metadata</h1><p>Local names and artwork remain highest priority. Online providers fill in canonical titles, descriptions, genres, ratings, posters, backdrops, seasons and episode information.</p>{metadataMessage&&<div className="settings-success">{metadataMessage}</div>}<div className="settings-card metadata-provider-card"><div className="provider-title"><div><strong>TMDB</strong><span className="primary-provider">Primary</span></div><span className={tmdb?.configured?'provider-connected':'provider-offline'}>{tmdb?.configured?'Configured':'Not configured'}</span></div><p>Recommended primary provider for Movies and TV. The token is stored in the operating-system credential store and is never sent to browser clients.</p><label className="setup-field"><span>API Read Access Token</span><input type="password" value={tmdbToken} onChange={e=>setTmdbTokenDraft(e.target.value)} placeholder={tmdb?.configured?'•••••••• configured — enter a new token to replace':'Paste TMDB API Read Access Token'}/></label><div className="metadata-actions"><button className="primary" disabled={metadataBusy||!tmdbToken.trim()} onClick={()=>void saveTmdb()}><Save size={16}/>Save & test</button>{tmdb?.configured&&<><button disabled={metadataBusy} onClick={async()=>{setMetadataBusy(true);try{await testTmdb();setMetadataMessage('TMDB connection is working.')}catch(c){setError(String(c))}finally{setMetadataBusy(false)}}}>Test connection</button><button disabled={metadataBusy} onClick={()=>void runAutoMatch()}><RefreshCw size={16}/>Match unmatched media</button><button className="danger-text" onClick={async()=>{await clearTmdbToken();setMetadataMessage('TMDB disconnected. Existing cached metadata remains available.');await refresh()}}>Disconnect</button></>}</div><p className="metadata-attribution">{tmdb?.attribution}</p></div><div className="settings-card metadata-provider-card disabled-provider"><div className="provider-title"><div><strong>TheTVDB</strong><span>Optional secondary provider</span></div><span className="provider-offline">Not enabled</span></div><p>Provider boundary is reserved for TheTVDB, particularly for alternate TV ordering or data that differs from TMDB. Onyx does not depend on it and it is not enabled in this milestone.</p><p className="metadata-attribution">{tvdb?.attribution}</p></div><div className="settings-card"><h3>Matching policy</h3><p>Onyx automatically accepts only high-confidence matches. Ambiguous files stay unmatched and can be resolved visually with <strong>Fix Match</strong>. A manual match is locked and will not be replaced by a rescan.</p></div></>}
 {category==='users'&&<><p className="eyebrow">PROFILES</p><h1>Users</h1><p>Profile names are editable, including the administrator. “Owner” is only the default name, not a locked display name.</p><div className="settings-user-list">{users.map(user=><div className="settings-card settings-user-row" key={user.id}><UserRound/><label><span>{user.isAdmin?'Administrator profile':'User profile'}</span><input value={nameDrafts[user.id]??user.name} onChange={e=>setNameDrafts(current=>({...current,[user.id]:e.target.value}))} onBlur={()=>void saveUserName(user)} onKeyDown={e=>{if(e.key==='Enter')void saveUserName(user)}}/></label><button className="icon-action" aria-label={`Save ${user.name}`} onClick={()=>void saveUserName(user)}><Save size={16}/></button><button onClick={()=>void chooseUser(user.id)}>{user.id===active?'Current':'Switch'}</button>{!user.isAdmin&&<button className="danger-text" onClick={()=>void removeUser(user)}>Delete</button>}</div>)}{newUserOpen?<div className="settings-card settings-user-row"><UserRound/><label><span>New user</span><input autoFocus value={newUserName} onChange={e=>setNewUserName(e.target.value)} placeholder="Name" onKeyDown={e=>{if(e.key==='Enter')void addUser();if(e.key==='Escape'){setNewUserOpen(false);setNewUserName('')}}}/></label><button className="icon-action" aria-label="Add user" onClick={()=>void addUser()}><Check size={16}/></button><button className="icon-action" aria-label="Cancel" onClick={()=>{setNewUserOpen(false);setNewUserName('')}}><X size={16}/></button></div>:<button onClick={()=>setNewUserOpen(true)}><Plus size={17}/>Add user</button>}</div></>}
 {category==='appearance'&&<><p className="eyebrow">PROFILE</p><h1>Appearance</h1><p>Theme settings belong to the current user.</p><div className="theme-choice-grid">{themes.map(value=><button key={value} className={`theme-choice theme-${value} ${theme===value?'active':''}`} onClick={()=>void chooseTheme(value)}><span/><strong>{value[0].toUpperCase()+value.slice(1)}</strong></button>)}</div></>}
 {category==='remote'&&<><p className="eyebrow">NETWORK</p><h1>Remote access</h1><div className="settings-card"><h3>Browser access</h3><p>LAN address: {status?.localUrl}</p><button onClick={()=>void password()}>{status?.accessPasswordSet?'Remove access password':'Set access password'}</button><p className="muted">Do not expose port 8765 directly to the internet. Use Tailscale or an HTTPS reverse proxy.</p></div></>}
 {category==='music'&&<><p className="eyebrow">PROVIDER</p><h1>iBroadcast</h1><p>iBroadcast is optional and isolated from the movie/TV library. In the iBroadcast web player open <strong>Apps → developer</strong>, create an Onyx developer app, save the required 128×128 PNG below, upload it, then copy the generated Client ID here.</p><IbroadcastLogoKit/><label className="setup-field"><span>Onyx iBroadcast client ID</span><input value={clientId} onChange={e=>setClientId(e.target.value)} placeholder="Client ID"/><button onClick={async()=>{try{await setIbroadcastClientId(clientId);await refresh()}catch(c){setError(String(c))}}}>Save</button></label><IbroadcastConnect onConnected={()=>void refresh()}/></>}
 {category==='cache'&&<><p className="eyebrow">STORAGE</p><h1>Cache</h1><div className="settings-card"><h3>Artwork</h3><p>{Math.round((status?.artworkCacheBytes??0)/1024/1024)} MB used</p><button onClick={async()=>{await clearThumbnailCache();await refresh()}}>Clear generated episode thumbnails</button></div></>}
 {category==='activity'&&<><p className="eyebrow">DIAGNOSTICS</p><h1>Activity Console</h1><p>Live server activity for troubleshooting and understanding what Onyx is doing. Credentials and access tokens are never written here.</p><div className="activity-toolbar"><span>{activity.length} recent events</span><div><button onClick={()=>void refreshActivity()}><RefreshCw size={16}/>Refresh</button><button onClick={async()=>{await clearActivity();await refreshActivity()}}>Clear</button></div></div><div className="activity-console">{activity.length===0?<div className="activity-empty">No activity recorded yet.</div>:activity.map((entry,index)=><div className="activity-row" key={`${entry.timestamp}-${index}`}><span className="activity-time">{new Date(entry.timestamp*1000).toLocaleTimeString()}</span><span className={`activity-level ${entry.level}`}>{entry.level}</span><span className="activity-category">{entry.category}</span><span className="activity-message">{entry.message}</span></div>)}</div></>}
 </section></div>;
}
