import { useEffect, useState } from 'react';
import { Check, KeyRound, Save, Trash2 } from 'lucide-react';
import { clearSubtitleProvider, getSubtitleProviderStatus, saveSubtitleProvider, testSubtitleProvider } from '../subtitleProviderApi';

export function SubtitleSettings(){
 const[configured,setConfigured]=useState(false);const[account,setAccount]=useState('');const[apiKey,setApiKey]=useState('');const[username,setUsername]=useState('');const[password,setPassword]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[message,setMessage]=useState<string|null>(null);
 const refresh=async()=>{const status=await getSubtitleProviderStatus();setConfigured(status.configured);setAccount(status.account);if(status.account&&!username)setUsername(status.account)};
 useEffect(()=>{void refresh().catch(c=>setError(String(c)))},[]);
 const save=async()=>{setBusy(true);setError(null);setMessage(null);try{await saveSubtitleProvider(apiKey.trim(),username.trim(),password);await testSubtitleProvider();setApiKey('');setPassword('');setMessage('OpenSubtitles connected successfully.');await refresh()}catch(c){setError(String(c))}finally{setBusy(false)}};
 const test=async()=>{setBusy(true);setError(null);setMessage(null);try{await testSubtitleProvider();setMessage('OpenSubtitles connection is working.')}catch(c){setError(String(c))}finally{setBusy(false)}};
 const disconnect=async()=>{setBusy(true);setError(null);try{await clearSubtitleProvider();setConfigured(false);setAccount('');setApiKey('');setUsername('');setPassword('');setMessage('OpenSubtitles disconnected. Existing downloaded subtitle files are unchanged.')}catch(c){setError(String(c))}finally{setBusy(false)}};
 return <><p className="eyebrow">SUBTITLES</p><h1>OpenSubtitles</h1>{message&&<div className="settings-success">{message}</div>}{error&&<div className="error-banner">{error}</div>}<div className="settings-card subtitle-provider-card"><div className="provider-title"><div><strong>OpenSubtitles.com</strong><span>Optional subtitle search and download</span></div><span className={configured?'provider-connected':'provider-offline'}>{configured?`Connected · ${account}`:'Not configured'}</span></div><div className="subtitle-credential-grid"><label><span>API key</span><input type="password" value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder={configured?'•••••••• configured — enter to replace':'OpenSubtitles application API key'}/></label><label><span>Username</span><input value={username} onChange={e=>setUsername(e.target.value)} placeholder="OpenSubtitles.com username"/></label><label><span>Password</span><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder={configured?'Enter only when replacing credentials':'OpenSubtitles.com password'}/></label></div><div className="metadata-actions"><button className="primary" disabled={busy||!apiKey.trim()||!username.trim()||!password} onClick={()=>void save()}><Save size={16}/>Save & test</button>{configured&&<><button disabled={busy} onClick={()=>void test()}><Check size={16}/>Test connection</button><button className="danger-text" disabled={busy} onClick={()=>void disconnect()}><Trash2 size={16}/>Disconnect</button></>}</div></div><div className="settings-card subtitle-provider-note"><KeyRound size={20}/><div><h3>How downloads are stored</h3><p>Onyx saves downloaded subtitles beside the media file when that folder is writable. If it is read-only, the subtitle is kept in Onyx-managed storage instead. Existing local and embedded subtitles always continue to work.</p></div></div></>;
}
