import { useEffect, useState } from 'react';
import { Download, Search, Subtitles, X } from 'lucide-react';
import type { MediaItem, SubtitleTrack } from '../types';
import { downloadOnlineSubtitle, getSubtitleProviderStatus, searchOnlineSubtitles, type SubtitleSearchResult } from '../subtitleProviderApi';
import '../subtitleFinder.css';

const languages=[['en','English'],['fr','French'],['es','Spanish'],['de','German'],['it','Italian'],['pt-br','Portuguese (Brazil)'],['ja','Japanese'],['ko','Korean']];

export function SubtitleFinder({item,onClose,onDownloaded}:{item:MediaItem;onClose:()=>void;onDownloaded:(track:SubtitleTrack)=>void}){
 const[language,setLanguage]=useState('en');const[results,setResults]=useState<SubtitleSearchResult[]>([]);const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[configured,setConfigured]=useState<boolean|null>(null);
 useEffect(()=>{getSubtitleProviderStatus().then(status=>setConfigured(status.configured)).catch(()=>setConfigured(false))},[]);
 const search=async()=>{setBusy(true);setError(null);try{setResults(await searchOnlineSubtitles(item.id,language))}catch(c){setError(String(c))}finally{setBusy(false)}};
 const download=async(result:SubtitleSearchResult)=>{setBusy(true);setError(null);try{const saved=await downloadOnlineSubtitle(item.id,result.fileId,result.language||language);onDownloaded({label:saved.label,language:saved.language,url:saved.url,embedded:false,forced:false,default:false,format:'srt'});onClose()}catch(c){setError(String(c))}finally{setBusy(false)}};
 return <div className="subtitle-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="subtitle-modal" role="dialog" aria-modal="true"><header><div><p className="eyebrow">SUBTITLES</p><h2>{item.kind==='episode'?`${item.showTitle} · ${item.title}`:item.title}</h2></div><button className="icon-action" aria-label="Close" onClick={onClose}><X size={18}/></button></header>{configured===false?<div className="subtitle-provider-missing"><Subtitles size={28}/><h3>OpenSubtitles is not configured</h3><p>Add your OpenSubtitles API key and account under Settings → Subtitles.</p></div>:<><div className="subtitle-search-row"><label><span>Language</span><select value={language} onChange={e=>setLanguage(e.target.value)}>{languages.map(([code,name])=><option key={code} value={code}>{name}</option>)}</select></label><button className="primary" disabled={busy} onClick={()=>void search()}><Search size={16}/>{busy?'Searching…':'Search'}</button></div>{error&&<div className="error-banner">{error}</div>}<div className="subtitle-results">{results.map(result=><article key={result.fileId}><div><strong>{result.release||result.fileName}</strong><span>{result.language.toUpperCase()}{result.hearingImpaired?' · SDH':''} · {result.downloadCount.toLocaleString()} downloads</span><small>{result.fileName}</small></div><button disabled={busy} title="Download subtitle" onClick={()=>void download(result)}><Download size={16}/>Download</button></article>)}{!busy&&configured&&results.length===0&&<div className="subtitle-empty">Search for subtitles in your preferred language.</div>}</div></>}</section></div>;
}
