use crate::{app_state::{persist_settings, Settings}, database, ibroadcast, metadata::tmdb, subtitles, Shared};
use aes_gcm::{aead::{Aead, KeyInit, OsRng, rand_core::RngCore}, Aes256Gcm, Nonce};
use argon2::Argon2;
use base64::{engine::general_purpose::STANDARD as B64, Engine};
use chrono::Utc;
use flate2::{Compression, read::GzDecoder, write::GzEncoder};
use rusqlite::Connection;
use serde::{Deserialize, Serialize};
use std::{collections::HashMap, fs, io::{Read, Write}, path::{Component, Path}};
use tauri::State;
use walkdir::WalkDir;

#[derive(Serialize, Deserialize)] struct Envelope { format:String, version:u8, created_at:i64, salt:String, nonce:String, ciphertext:String }
#[derive(Serialize, Deserialize)] struct StoredFile { path:String, data:String }
#[derive(Default, Serialize, Deserialize)] struct Credentials { tmdb:Option<String>, subtitles:Option<String>, ibroadcast:HashMap<String,String> }
#[derive(Serialize, Deserialize)] struct Payload { settings:Settings, database:String, provider_files:Vec<StoredFile>, credentials:Credentials }
#[derive(Serialize)] #[serde(rename_all="camelCase")] pub struct BackupPreview { created_at:i64, movie_paths:Vec<String>, tv_paths:Vec<String>, special_paths:Vec<String>, media_items:usize, users:usize, includes_tmdb:bool, includes_subtitles:bool, includes_ibroadcast:bool }
#[derive(Deserialize)] #[serde(rename_all="camelCase")] pub struct RootMapping { from:String, to:String }
#[derive(Serialize)] #[serde(rename_all="camelCase")] pub struct RestoreReport { media_items:usize, users:usize, remapped_roots:usize, safety_backup_path:String }

fn key(password:&str,salt:&[u8])->Result<[u8;32],String>{if password.len()<10{return Err("Backup password must be at least 10 characters.".into())}let mut key=[0u8;32];Argon2::default().hash_password_into(password.as_bytes(),salt,&mut key).map_err(|e|e.to_string())?;Ok(key)}
fn provider_files(root:&Path)->Result<Vec<StoredFile>,String>{let mut out=vec![];if !root.exists(){return Ok(out)}for item in WalkDir::new(root).into_iter().filter_map(Result::ok).filter(|v|v.file_type().is_file()){let rel=item.path().strip_prefix(root).map_err(|e|e.to_string())?.to_string_lossy().replace('\\',"/");out.push(StoredFile{path:rel,data:B64.encode(fs::read(item.path()).map_err(|e|e.to_string())?)})}Ok(out)}
fn database_snapshot(path:&Path)->Result<Vec<u8>,String>{let _=Connection::open(path).and_then(|c|c.execute_batch("PRAGMA wal_checkpoint(FULL);"));fs::read(path).map_err(|e|format!("Could not read database: {e}"))}
fn build_payload(state:&crate::app_state::AppState)->Result<Payload,String>{let settings=state.settings.read().map_err(|_|"Settings lock poisoned")?.clone();let mut credentials=Credentials{tmdb:tmdb::export_token(),subtitles:subtitles::export_credentials(),..Default::default()};for user in database::list_users(&state.database_path)?{if let Some(raw)=ibroadcast::export_token(&user.id){credentials.ibroadcast.insert(user.id,raw);}}Ok(Payload{settings,database:B64.encode(database_snapshot(&state.database_path)?),provider_files:provider_files(&state.provider_path)?,credentials})}
fn encode(payload:&Payload,password:&str)->Result<Vec<u8>,String>{let raw=serde_json::to_vec(payload).map_err(|e|e.to_string())?;let mut gz=GzEncoder::new(Vec::new(),Compression::default());gz.write_all(&raw).map_err(|e|e.to_string())?;let compressed=gz.finish().map_err(|e|e.to_string())?;let mut salt=[0u8;16];let mut nonce=[0u8;12];OsRng.fill_bytes(&mut salt);OsRng.fill_bytes(&mut nonce);let cipher=Aes256Gcm::new_from_slice(&key(password,&salt)?).map_err(|e|e.to_string())?;let ciphertext=cipher.encrypt(Nonce::from_slice(&nonce),compressed.as_ref()).map_err(|_|"Could not encrypt backup".to_string())?;serde_json::to_vec_pretty(&Envelope{format:"onyx-backup".into(),version:1,created_at:Utc::now().timestamp(),salt:B64.encode(salt),nonce:B64.encode(nonce),ciphertext:B64.encode(ciphertext)}).map_err(|e|e.to_string())}
fn decode(path:&Path,password:&str)->Result<(Envelope,Payload),String>{let envelope:Envelope=serde_json::from_slice(&fs::read(path).map_err(|e|format!("Could not read backup: {e}"))?).map_err(|_|"This is not a valid Onyx backup.".to_string())?;if envelope.format!="onyx-backup"||envelope.version!=1{return Err("This Onyx backup version is not supported.".into())}let salt=B64.decode(&envelope.salt).map_err(|_|"Backup salt is invalid")?;let nonce=B64.decode(&envelope.nonce).map_err(|_|"Backup nonce is invalid")?;let encrypted=B64.decode(&envelope.ciphertext).map_err(|_|"Backup data is invalid")?;let cipher=Aes256Gcm::new_from_slice(&key(password,&salt)?).map_err(|e|e.to_string())?;let compressed=cipher.decrypt(Nonce::from_slice(&nonce),encrypted.as_ref()).map_err(|_|"The backup password is incorrect or the file is damaged.".to_string())?;let mut decoder=GzDecoder::new(compressed.as_slice());let mut raw=vec![];decoder.read_to_end(&mut raw).map_err(|_|"The backup contents are damaged.".to_string())?;let payload=serde_json::from_slice(&raw).map_err(|_|"The backup contents are invalid.".to_string())?;Ok((envelope,payload))}
fn write_archive(state:&crate::app_state::AppState,path:&Path,password:&str)->Result<(),String>{if let Some(parent)=path.parent(){fs::create_dir_all(parent).map_err(|e|e.to_string())?}fs::write(path,encode(&build_payload(state)?,password)?).map_err(|e|format!("Could not write backup: {e}"))}
fn mapped(value:&str,mappings:&[RootMapping])->String{for mapping in mappings{let from=mapping.from.trim_end_matches(['\\','/']);if value.eq_ignore_ascii_case(from)||value.starts_with(&format!("{from}\\"))||value.starts_with(&format!("{from}/")){return format!("{}{}",mapping.to.trim_end_matches(['\\','/']),&value[from.len()..])}}value.to_string()}
fn merge_databases(current:&Path,imported:&Path)->Result<(),String>{let conn=Connection::open(current).map_err(|e|e.to_string())?;conn.execute("ATTACH DATABASE ?1 AS imported",[imported.to_string_lossy().as_ref()]).map_err(|e|e.to_string())?;let tables:Vec<String>={let mut stmt=conn.prepare("SELECT name FROM imported.sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'").map_err(|e|e.to_string())?;let mut rows=stmt.query([]).map_err(|e|e.to_string())?;let mut names=vec![];while let Some(row)=rows.next().map_err(|e|e.to_string())?{names.push(row.get(0).map_err(|e|e.to_string())?)}names};conn.execute_batch("PRAGMA foreign_keys=OFF;BEGIN IMMEDIATE;").map_err(|e|e.to_string())?;for table in tables{if !table.chars().all(|c|c.is_ascii_alphanumeric()||c=='_'){continue}let sql=format!("INSERT OR REPLACE INTO main.{table} SELECT * FROM imported.{table}");let _=conn.execute(&sql,[]);}conn.execute_batch("COMMIT;PRAGMA foreign_keys=ON;").map_err(|e|e.to_string())?;Ok(())}

#[tauri::command] pub fn backup_create(state:State<'_,Shared>,path:String,password:String)->Result<BackupPreview,String>{write_archive(&state,Path::new(&path),&password)?;backup_preview(path,password)}
#[tauri::command] pub fn backup_preview(path:String,password:String)->Result<BackupPreview,String>{let (envelope,payload)=decode(Path::new(&path),&password)?;let bytes=B64.decode(&payload.database).map_err(|_|"Backup database is damaged")?;let temp=std::env::temp_dir().join(format!("onyx-preview-{}.db",uuid::Uuid::new_v4()));fs::write(&temp,bytes).map_err(|e|e.to_string())?;let media_items=database::load_library(&temp).map(|v|v.len()).unwrap_or(0);let users=database::list_users(&temp).map(|v|v.len()).unwrap_or(0);let _=fs::remove_file(temp);Ok(BackupPreview{created_at:envelope.created_at,movie_paths:payload.settings.effective_movie_paths(),tv_paths:payload.settings.effective_tv_paths(),special_paths:payload.settings.effective_special_paths(),media_items,users,includes_tmdb:payload.credentials.tmdb.is_some(),includes_subtitles:payload.credentials.subtitles.is_some(),includes_ibroadcast:!payload.credentials.ibroadcast.is_empty()})}
#[tauri::command] pub fn backup_restore(state:State<'_,Shared>,path:String,password:String,mode:String,mappings:Vec<RootMapping>)->Result<RestoreReport,String>{if state.scan_progress.read().map_err(|_|"Scan lock poisoned")?.active{return Err("Wait for the current library scan to finish before restoring.".into())}let (_,mut payload)=decode(Path::new(&path),&password)?;let source=Path::new(&path);let safety=source.parent().unwrap_or(Path::new(".")).join(format!("Onyx-pre-restore-{}.onyx-backup",Utc::now().format("%Y%m%d-%H%M%S")));write_archive(&state,&safety,&password)?;payload.settings.movie_paths=payload.settings.effective_movie_paths().iter().map(|v|mapped(v,&mappings)).collect();payload.settings.tv_paths=payload.settings.effective_tv_paths().iter().map(|v|mapped(v,&mappings)).collect();payload.settings.movie_path=None;payload.settings.tv_path=None;if mode=="merge"{let current=state.settings.read().map_err(|_|"Settings lock poisoned")?.clone();payload.settings.movie_paths.extend(current.effective_movie_paths());payload.settings.tv_paths.extend(current.effective_tv_paths());payload.settings.movie_paths.sort();payload.settings.movie_paths.dedup();payload.settings.tv_paths.sort();payload.settings.tv_paths.dedup();}
 let imported=std::env::temp_dir().join(format!("onyx-import-{}.db",uuid::Uuid::new_v4()));fs::write(&imported,B64.decode(&payload.database).map_err(|_|"Backup database is damaged")?).map_err(|e|e.to_string())?;for mapping in &mappings{Connection::open(&imported).and_then(|c|c.execute("UPDATE media SET path=?1 || substr(path,length(?2)+1) WHERE lower(path)=lower(?2) OR lower(path) LIKE lower(?2 || '/%') OR lower(path) LIKE lower(?2 || '\\%')",[mapping.to.as_str(),mapping.from.as_str()])).map_err(|e|e.to_string())?;}if mode=="merge"{merge_databases(&state.database_path,&imported)?;}else{let _=Connection::open(&state.database_path).and_then(|c|c.execute_batch("PRAGMA wal_checkpoint(TRUNCATE);"));fs::copy(&imported,&state.database_path).map_err(|e|format!("Could not restore database: {e}"))?;}let _=fs::remove_file(imported);for file in payload.provider_files{let relative=Path::new(&file.path);if relative.components().any(|part|matches!(part,Component::ParentDir|Component::RootDir|Component::Prefix(_))){return Err("Backup contains an unsafe provider path.".into())}let destination=state.provider_path.join(relative);if let Some(parent)=destination.parent(){fs::create_dir_all(parent).map_err(|e|e.to_string())?}fs::write(destination,B64.decode(file.data).map_err(|_|"A provider file is damaged")?).map_err(|e|e.to_string())?;}if let Some(token)=payload.credentials.tmdb{tmdb::import_token(&token)?}if let Some(raw)=payload.credentials.subtitles{subtitles::import_credentials(&raw)?}for(user,raw)in payload.credentials.ibroadcast{ibroadcast::import_token(&user,&raw)?}*state.settings.write().map_err(|_|"Settings lock poisoned")?=payload.settings;persist_settings(&state)?;database::init(&state.database_path)?;crate::metadata::init(&state.database_path)?;crate::user_features::init(&state.database_path)?;let media=database::load_library(&state.database_path)?;let users=database::list_users(&state.database_path)?.len();let media_items=media.len();*state.media.write().map_err(|_|"Media lock poisoned")?=media;Ok(RestoreReport{media_items,users,remapped_roots:mappings.len(),safety_backup_path:safety.to_string_lossy().to_string()})}
