use crate::models::{MediaItem, Playlist, UserProfile};
use rusqlite::{params, Connection, OptionalExtension};
use std::{collections::{HashMap, HashSet}, path::Path};
use uuid::Uuid;

pub const DEFAULT_USER_ID: &str = "owner";

#[derive(Clone, Debug, Default)]
pub struct IdentityOverride {
    pub title: Option<String>, pub year: Option<u16>, pub kind: Option<String>, pub show_title: Option<String>, pub season: Option<u16>, pub episode: Option<u16>,
}

pub fn init(path: &Path) -> Result<(), String> {
    if let Some(parent) = path.parent() { std::fs::create_dir_all(parent).map_err(|e| e.to_string())?; }
    let conn = Connection::open(path).map_err(|e| e.to_string())?;
    conn.execute_batch(
        "PRAGMA journal_mode=WAL;
         PRAGMA foreign_keys=ON;
         CREATE TABLE IF NOT EXISTS media (id TEXT PRIMARY KEY,path TEXT NOT NULL UNIQUE,kind TEXT NOT NULL,show_title TEXT,season INTEGER,episode INTEGER,metadata_json TEXT NOT NULL,updated_at INTEGER NOT NULL DEFAULT (unixepoch()));
         CREATE TABLE IF NOT EXISTS progress (media_id TEXT PRIMARY KEY,seconds INTEGER NOT NULL DEFAULT 0,updated_at INTEGER NOT NULL DEFAULT (unixepoch()));
         CREATE TABLE IF NOT EXISTS identity_overrides (media_id TEXT PRIMARY KEY,title TEXT,year INTEGER,kind TEXT,show_title TEXT,season INTEGER,episode INTEGER,updated_at INTEGER NOT NULL DEFAULT (unixepoch()));
         CREATE TABLE IF NOT EXISTS show_overrides (root_path TEXT PRIMARY KEY,show_title TEXT NOT NULL,updated_at INTEGER NOT NULL DEFAULT (unixepoch()));
         CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY,name TEXT NOT NULL UNIQUE COLLATE NOCASE,is_admin INTEGER NOT NULL DEFAULT 0,created_at INTEGER NOT NULL DEFAULT (unixepoch()));
         CREATE TABLE IF NOT EXISTS user_progress (user_id TEXT NOT NULL,media_id TEXT NOT NULL,seconds INTEGER NOT NULL DEFAULT 0,updated_at INTEGER NOT NULL DEFAULT (unixepoch()),PRIMARY KEY(user_id,media_id),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
         CREATE TABLE IF NOT EXISTS user_hidden (user_id TEXT NOT NULL,target_type TEXT NOT NULL,target_key TEXT NOT NULL,created_at INTEGER NOT NULL DEFAULT (unixepoch()),PRIMARY KEY(user_id,target_type,target_key),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
         CREATE TABLE IF NOT EXISTS user_playlists (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,name TEXT NOT NULL,created_at INTEGER NOT NULL DEFAULT (unixepoch()),UNIQUE(user_id,name),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
         CREATE TABLE IF NOT EXISTS user_playlist_items (playlist_id TEXT NOT NULL,media_id TEXT NOT NULL,position INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(playlist_id,media_id),FOREIGN KEY(playlist_id) REFERENCES user_playlists(id) ON DELETE CASCADE);
         CREATE INDEX IF NOT EXISTS idx_media_kind ON media(kind);
         CREATE INDEX IF NOT EXISTS idx_media_show ON media(show_title,season,episode);
         CREATE INDEX IF NOT EXISTS idx_user_progress ON user_progress(user_id,media_id);
         CREATE INDEX IF NOT EXISTS idx_user_hidden ON user_hidden(user_id,target_type,target_key);
         CREATE INDEX IF NOT EXISTS idx_user_playlist_items ON user_playlist_items(playlist_id,position);"
    ).map_err(|e| e.to_string())?;
    conn.execute("INSERT OR IGNORE INTO users(id,name,is_admin) VALUES(?1,'Owner',1)",[DEFAULT_USER_ID]).map_err(|e|e.to_string())?;
    let migrated: i64 = conn.query_row("SELECT COUNT(*) FROM user_progress WHERE user_id=?1",[DEFAULT_USER_ID],|r|r.get(0)).map_err(|e|e.to_string())?;
    if migrated == 0 { conn.execute("INSERT OR IGNORE INTO user_progress(user_id,media_id,seconds,updated_at) SELECT ?1,media_id,seconds,updated_at FROM progress",[DEFAULT_USER_ID]).map_err(|e|e.to_string())?; }
    Ok(())
}

pub fn list_users(path:&Path)->Result<Vec<UserProfile>,String>{let conn=Connection::open(path).map_err(|e|e.to_string())?;let mut stmt=conn.prepare("SELECT id,name,is_admin FROM users ORDER BY is_admin DESC,lower(name)").map_err(|e|e.to_string())?;let rows=stmt.query_map([],|r|Ok(UserProfile{id:r.get(0)?,name:r.get(1)?,is_admin:r.get::<_,i64>(2)?!=0})).map_err(|e|e.to_string())?;let mut out=Vec::new();for row in rows{out.push(row.map_err(|e|e.to_string())?);}Ok(out)}
pub fn user_exists(path:&Path,user_id:&str)->bool{Connection::open(path).ok().and_then(|c|c.query_row("SELECT 1 FROM users WHERE id=?1",[user_id],|r|r.get::<_,i64>(0)).optional().ok().flatten()).is_some()}
pub fn create_user(path:&Path,name:&str)->Result<Vec<UserProfile>,String>{let name=name.trim();if name.is_empty(){return Err("User name cannot be empty".into())}let id=Uuid::new_v4().to_string();Connection::open(path).map_err(|e|e.to_string())?.execute("INSERT INTO users(id,name,is_admin) VALUES(?1,?2,0)",params![id,name]).map_err(|e|e.to_string())?;list_users(path)}
pub fn delete_user(path:&Path,user_id:&str)->Result<Vec<UserProfile>,String>{if user_id==DEFAULT_USER_ID{return Err("The Owner profile cannot be deleted".into())}Connection::open(path).map_err(|e|e.to_string())?.execute("DELETE FROM users WHERE id=?1",[user_id]).map_err(|e|e.to_string())?;list_users(path)}

pub fn progress_map_for_user(path:&Path,user_id:&str)->Result<HashMap<String,u64>,String>{let conn=Connection::open(path).map_err(|e|e.to_string())?;let mut stmt=conn.prepare("SELECT media_id,seconds FROM user_progress WHERE user_id=?1").map_err(|e|e.to_string())?;let rows=stmt.query_map([user_id],|r|Ok((r.get::<_,String>(0)?,r.get::<_,u64>(1)?))).map_err(|e|e.to_string())?;let mut out=HashMap::new();for row in rows{let(k,v)=row.map_err(|e|e.to_string())?;out.insert(k,v);}Ok(out)}
pub fn save_progress(path:&Path,user_id:&str,id:&str,seconds:u64)->Result<(),String>{Connection::open(path).map_err(|e|e.to_string())?.execute("INSERT INTO user_progress(user_id,media_id,seconds,updated_at) VALUES(?1,?2,?3,unixepoch()) ON CONFLICT(user_id,media_id) DO UPDATE SET seconds=excluded.seconds,updated_at=unixepoch()",params![user_id,id,seconds]).map_err(|e|e.to_string())?;Ok(())}
pub fn reset_progress(path:&Path,user_id:&str,ids:&[String])->Result<(),String>{let mut conn=Connection::open(path).map_err(|e|e.to_string())?;let tx=conn.transaction().map_err(|e|e.to_string())?;{let mut stmt=tx.prepare("DELETE FROM user_progress WHERE user_id=?1 AND media_id=?2").map_err(|e|e.to_string())?;for id in ids{stmt.execute(params![user_id,id]).map_err(|e|e.to_string())?;}}tx.commit().map_err(|e|e.to_string())}

pub fn hidden_sets(path:&Path,user_id:&str)->Result<(HashSet<String>,HashSet<String>),String>{let conn=Connection::open(path).map_err(|e|e.to_string())?;let mut stmt=conn.prepare("SELECT target_type,target_key FROM user_hidden WHERE user_id=?1").map_err(|e|e.to_string())?;let rows=stmt.query_map([user_id],|r|Ok((r.get::<_,String>(0)?,r.get::<_,String>(1)?))).map_err(|e|e.to_string())?;let(mut media,mut shows)=(HashSet::new(),HashSet::new());for row in rows{let(t,k)=row.map_err(|e|e.to_string())?;if t=="media"{media.insert(k);}else if t=="show"{shows.insert(k);}}Ok((media,shows))}
pub fn set_hidden(path:&Path,user_id:&str,target_type:&str,target_key:&str,hidden:bool)->Result<(),String>{if !["media","show"].contains(&target_type){return Err("Invalid hidden target".into())}let conn=Connection::open(path).map_err(|e|e.to_string())?;if hidden{conn.execute("INSERT OR IGNORE INTO user_hidden(user_id,target_type,target_key) VALUES(?1,?2,?3)",params![user_id,target_type,target_key]).map_err(|e|e.to_string())?;}else{conn.execute("DELETE FROM user_hidden WHERE user_id=?1 AND target_type=?2 AND target_key=?3",params![user_id,target_type,target_key]).map_err(|e|e.to_string())?;}Ok(())}

pub fn identity_overrides(path:&Path)->Result<HashMap<String,IdentityOverride>,String>{let conn=Connection::open(path).map_err(|e|e.to_string())?;let mut stmt=conn.prepare("SELECT media_id,title,year,kind,show_title,season,episode FROM identity_overrides").map_err(|e|e.to_string())?;let rows=stmt.query_map([],|row|Ok((row.get::<_,String>(0)?,IdentityOverride{title:row.get(1)?,year:row.get(2)?,kind:row.get(3)?,show_title:row.get(4)?,season:row.get(5)?,episode:row.get(6)?}))).map_err(|e|e.to_string())?;let mut values=HashMap::new();for row in rows{let(id,value)=row.map_err(|e|e.to_string())?;values.insert(id,value);}Ok(values)}
pub fn show_overrides(path:&Path)->Result<Vec<(String,String)>,String>{let conn=Connection::open(path).map_err(|e|e.to_string())?;let mut stmt=conn.prepare("SELECT root_path,show_title FROM show_overrides ORDER BY length(root_path) DESC").map_err(|e|e.to_string())?;let rows=stmt.query_map([],|row|Ok((row.get::<_,String>(0)?,row.get::<_,String>(1)?))).map_err(|e|e.to_string())?;let mut values=Vec::new();for row in rows{values.push(row.map_err(|e|e.to_string())?);}Ok(values)}
pub fn save_identity_override(path:&Path,id:&str,value:&IdentityOverride)->Result<(),String>{Connection::open(path).map_err(|e|e.to_string())?.execute("INSERT INTO identity_overrides(media_id,title,year,kind,show_title,season,episode,updated_at)VALUES(?1,?2,?3,?4,?5,?6,?7,unixepoch()) ON CONFLICT(media_id) DO UPDATE SET title=excluded.title,year=excluded.year,kind=excluded.kind,show_title=excluded.show_title,season=excluded.season,episode=excluded.episode,updated_at=unixepoch()",params![id,value.title.as_deref(),value.year,value.kind.as_deref(),value.show_title.as_deref(),value.season,value.episode]).map_err(|e|e.to_string())?;Ok(())}
pub fn clear_identity_override(path:&Path,id:&str)->Result<(),String>{Connection::open(path).map_err(|e|e.to_string())?.execute("DELETE FROM identity_overrides WHERE media_id=?1",[id]).map_err(|e|e.to_string())?;Ok(())}
pub fn save_show_override(path:&Path,root_path:&str,show_title:&str)->Result<(),String>{Connection::open(path).map_err(|e|e.to_string())?.execute("INSERT INTO show_overrides(root_path,show_title,updated_at)VALUES(?1,?2,unixepoch()) ON CONFLICT(root_path) DO UPDATE SET show_title=excluded.show_title,updated_at=unixepoch()",params![root_path,show_title]).map_err(|e|e.to_string())?;Ok(())}

pub fn replace_library(path:&Path,items:&[MediaItem])->Result<(),String>{let mut conn=Connection::open(path).map_err(|e|e.to_string())?;let tx=conn.transaction().map_err(|e|e.to_string())?;tx.execute("DELETE FROM media",[]).map_err(|e|e.to_string())?;{let mut stmt=tx.prepare("INSERT INTO media(id,path,kind,show_title,season,episode,metadata_json,updated_at)VALUES(?1,?2,?3,?4,?5,?6,?7,unixepoch())").map_err(|e|e.to_string())?;for item in items{let mut stored=item.clone();stored.progress_seconds=0;let json=serde_json::to_string(&stored).map_err(|e|e.to_string())?;stmt.execute(params![&item.id,&item.path,&item.kind,item.show_title.as_deref(),item.season,item.episode,json]).map_err(|e|e.to_string())?;}}tx.commit().map_err(|e|e.to_string())}
pub fn load_library(path:&Path)->Result<Vec<MediaItem>,String>{load_library_for_user(path,DEFAULT_USER_ID,true)}
pub fn load_library_for_user(path:&Path,user_id:&str,include_hidden:bool)->Result<Vec<MediaItem>,String>{let conn=Connection::open(path).map_err(|e|e.to_string())?;let progress=progress_map_for_user(path,user_id).unwrap_or_default();let(hidden_media,hidden_shows)=hidden_sets(path,user_id).unwrap_or_default();let mut stmt=conn.prepare("SELECT metadata_json FROM media ORDER BY COALESCE(show_title,''),COALESCE(season,0),COALESCE(episode,0),path").map_err(|e|e.to_string())?;let rows=stmt.query_map([],|r|r.get::<_,String>(0)).map_err(|e|e.to_string())?;let mut items=Vec::new();for row in rows{let json=row.map_err(|e|e.to_string())?;let mut item:MediaItem=serde_json::from_str(&json).map_err(|e|e.to_string())?;if !include_hidden&&(hidden_media.contains(&item.id)||item.show_title.as_ref().is_some_and(|s|hidden_shows.contains(s))){continue}item.progress_seconds=*progress.get(&item.id).unwrap_or(&0);items.push(item);}Ok(items)}

pub fn list_playlists(path:&Path,user_id:&str)->Result<Vec<Playlist>,String>{let conn=Connection::open(path).map_err(|e|e.to_string())?;let mut stmt=conn.prepare("SELECT id,name FROM user_playlists WHERE user_id=?1 ORDER BY lower(name)").map_err(|e|e.to_string())?;let rows=stmt.query_map([user_id],|r|Ok((r.get::<_,String>(0)?,r.get::<_,String>(1)?))).map_err(|e|e.to_string())?;let mut result=Vec::new();for row in rows{let(id,name)=row.map_err(|e|e.to_string())?;let mut item_stmt=conn.prepare("SELECT media_id FROM user_playlist_items WHERE playlist_id=?1 ORDER BY position,rowid").map_err(|e|e.to_string())?;let item_rows=item_stmt.query_map([&id],|r|r.get::<_,String>(0)).map_err(|e|e.to_string())?;let mut media_ids=Vec::new();for item in item_rows{media_ids.push(item.map_err(|e|e.to_string())?);}result.push(Playlist{id,name,media_ids});}Ok(result)}
pub fn create_playlist(path:&Path,user_id:&str,name:&str)->Result<Playlist,String>{let trimmed=name.trim();if trimmed.is_empty(){return Err("Playlist name cannot be empty".into())}let id=Uuid::new_v4().to_string();Connection::open(path).map_err(|e|e.to_string())?.execute("INSERT INTO user_playlists(id,user_id,name)VALUES(?1,?2,?3)",params![&id,user_id,trimmed]).map_err(|e|e.to_string())?;Ok(Playlist{id,name:trimmed.to_string(),media_ids:vec![]})}
pub fn add_playlist_item(path:&Path,user_id:&str,playlist_id:&str,media_id:&str)->Result<(),String>{let conn=Connection::open(path).map_err(|e|e.to_string())?;let owner:Option<String>=conn.query_row("SELECT user_id FROM user_playlists WHERE id=?1",[playlist_id],|r|r.get(0)).optional().map_err(|e|e.to_string())?;if owner.as_deref()!=Some(user_id){return Err("Playlist not found".into())}let position:i64=conn.query_row("SELECT COALESCE(MAX(position),-1)+1 FROM user_playlist_items WHERE playlist_id=?1",[playlist_id],|r|r.get(0)).map_err(|e|e.to_string())?;conn.execute("INSERT OR IGNORE INTO user_playlist_items(playlist_id,media_id,position)VALUES(?1,?2,?3)",params![playlist_id,media_id,position]).map_err(|e|e.to_string())?;Ok(())}
pub fn remove_playlist_item(path:&Path,user_id:&str,playlist_id:&str,media_id:&str)->Result<(),String>{let conn=Connection::open(path).map_err(|e|e.to_string())?;conn.execute("DELETE FROM user_playlist_items WHERE playlist_id IN (SELECT id FROM user_playlists WHERE id=?1 AND user_id=?2) AND media_id=?3",params![playlist_id,user_id,media_id]).map_err(|e|e.to_string())?;Ok(())}
pub fn delete_playlist(path:&Path,user_id:&str,playlist_id:&str)->Result<(),String>{let conn=Connection::open(path).map_err(|e|e.to_string())?;conn.execute("DELETE FROM user_playlist_items WHERE playlist_id IN (SELECT id FROM user_playlists WHERE id=?1 AND user_id=?2)",params![playlist_id,user_id]).map_err(|e|e.to_string())?;conn.execute("DELETE FROM user_playlists WHERE id=?1 AND user_id=?2",params![playlist_id,user_id]).map_err(|e|e.to_string())?;Ok(())}
