use axum::{extract::{Path,State},http::StatusCode,routing::{get,post},Json,Router};
use serde::{Deserialize,Serialize};
use std::{collections::HashMap,net::SocketAddr,sync::{Arc,RwLock},time::{SystemTime,UNIX_EPOCH}};
use uuid::Uuid;

const REMOTE_SECONDS:u64=60*60*8;
#[derive(Clone,Default)]pub struct RemoteRuntime(pub Arc<RwLock<HashMap<String,RemoteSession>>>);
#[derive(Clone,Serialize)]#[serde(rename_all="camelCase")]struct RemoteSession{token:String,code:String,remote_url:String,expires_at:u64,projector_connected:bool,controller_count:u32,sequence:u64,command:Option<String>,now_playing:Option<NowPlaying>,sleep_until:Option<u64>,sleeping:bool,last_controller_at:u64,last_projector_at:u64}
#[derive(Clone,Serialize,Deserialize)]#[serde(rename_all="camelCase")]struct NowPlaying{title:String,subtitle:Option<String>,artwork:Option<String>,paused:Option<bool>,current_time:Option<f64>,duration:Option<f64>,volume:Option<f64>,live:Option<bool>}
#[derive(Deserialize)]struct CommandPayload{command:String}
#[derive(Deserialize)]#[serde(rename_all="camelCase")]struct StatePayload{now_playing:Option<NowPlaying>,sleep_until:Option<u64>,sleeping:Option<bool>,projector_connected:Option<bool>}
#[derive(Serialize)]#[serde(rename_all="camelCase")]struct CreateResponse{token:String,code:String,remote_url:String,expires_at:u64}
fn now()->u64{SystemTime::now().duration_since(UNIX_EPOCH).map(|v|v.as_secs()).unwrap_or(0)}
fn clean(runtime:&RemoteRuntime){if let Ok(mut sessions)=runtime.0.write(){let t=now();sessions.retain(|_,s|s.expires_at>t)}}
async fn create(State(runtime):State<RemoteRuntime>)->Result<Json<CreateResponse>,StatusCode>{clean(&runtime);let token=Uuid::new_v4().simple().to_string();let code=token[..4].to_ascii_uppercase();let expires=now()+REMOTE_SECONDS;let session=RemoteSession{token:token.clone(),code:code.clone(),remote_url:format!("/remote/{token}"),expires_at:expires,projector_connected:true,controller_count:0,sequence:0,command:None,now_playing:None,sleep_until:None,sleeping:false,last_controller_at:0,last_projector_at:now()};runtime.0.write().map_err(|_|StatusCode::INTERNAL_SERVER_ERROR)?.insert(token.clone(),session);Ok(Json(CreateResponse{token,code,remote_url:format!("/remote/{token}"),expires_at:expires}))}
fn snapshot(runtime:&RemoteRuntime,token:&str,controller:bool)->Result<RemoteSession,StatusCode>{clean(runtime);let mut sessions=runtime.0.write().map_err(|_|StatusCode::INTERNAL_SERVER_ERROR)?;let s=sessions.get_mut(token).ok_or(StatusCode::NOT_FOUND)?;let t=now();if controller{s.last_controller_at=t;s.controller_count=1}else{s.last_projector_at=t;s.projector_connected=true}if t.saturating_sub(s.last_controller_at)>5{s.controller_count=0}if t.saturating_sub(s.last_projector_at)>5{s.projector_connected=false}Ok(s.clone())}
async fn state_get(State(runtime):State<RemoteRuntime>,Path(token):Path<String>)->Result<Json<RemoteSession>,StatusCode>{snapshot(&runtime,&token,true).map(Json)}
async fn state_post(State(runtime):State<RemoteRuntime>,Path(token):Path<String>,Json(payload):Json<StatePayload>)->Result<Json<RemoteSession>,StatusCode>{clean(&runtime);{let mut sessions=runtime.0.write().map_err(|_|StatusCode::INTERNAL_SERVER_ERROR)?;let s=sessions.get_mut(&token).ok_or(StatusCode::NOT_FOUND)?;if let Some(value)=payload.now_playing{s.now_playing=Some(value)}if let Some(value)=payload.sleep_until{s.sleep_until=Some(value)}if let Some(value)=payload.sleeping{s.sleeping=value}if payload.projector_connected.unwrap_or(true){s.projector_connected=true}s.last_projector_at=now();}snapshot(&runtime,&token,false).map(Json)}
async fn command(State(runtime):State<RemoteRuntime>,Path(token):Path<String>,Json(payload):Json<CommandPayload>)->Result<Json<RemoteSession>,StatusCode>{clean(&runtime);{let mut sessions=runtime.0.write().map_err(|_|StatusCode::INTERNAL_SERVER_ERROR)?;let s=sessions.get_mut(&token).ok_or(StatusCode::NOT_FOUND)?;s.sequence+=1;s.command=Some(payload.command);s.last_controller_at=now();s.controller_count=1;}snapshot(&runtime,&token,true).map(Json)}
pub async fn start(port:u16){let runtime=RemoteRuntime::default();let app=Router::new().route("/api/remote/session",post(create)).route("/api/remote/{token}/state",get(state_get).post(state_post)).route("/api/remote/{token}/command",post(command)).with_state(runtime);let address=SocketAddr::from(([0,0,0,0],port));match tokio::net::TcpListener::bind(address).await{Ok(listener)=>{let _=axum::serve(listener,app).await;}Err(error)=>eprintln!("Onyx remote server failed to bind: {error}")}}
