import { invoke } from '@tauri-apps/api/core';
import type { AnalyticsSummary, AuthStatus, IbConnectionStatus, IbDeviceCode, IbDevicePoll, IbLibrary, MediaItem, Playlist, ServerStatus, SetupStatus, ThemeName, UserPreferences, UserProfile } from './types';
export interface IdentityInput { title?:string; year?:number; kind?:'movie'|'episode'; showTitle?:string; season?:number; episode?:number; }
export const isTauriDesktop=()=>Boolean((window as Window&{__TAURI_INTERNALS__?:unknown}).__TAURI_INTERNALS__);
export const serverBaseUrl=()=>isTauriDesktop()?'http://127.0.0.1:8765':'';
export const resolveMediaUrl=(url?:string|null)=>{if(!url)return undefined;if(/^https?:\/\//i.test(url))return url;return `${serverBaseUrl()}${url.startsWith('/')?url:`/${url}`}`;};
let activeUserId=localStorage.getItem('onyx-user')||localStorage.getItem('home-media-user')||'owner';
export const getActiveUserId=()=>activeUserId;
export const setActiveUserId=(id:string)=>{activeUserId=id;localStorage.setItem('onyx-user',id);};
const userHeaders=(extra:Record<string,string>={})=>({'x-home-media-user':activeUserId,...extra});
const browserFetch=(input:string,init?:RequestInit)=>fetch(input,{...init,credentials:'include',headers:{...userHeaders(),...((init?.headers as Record<string,string>|undefined)??{})}});
async function json<T>(response:Response,message:string):Promise<T>{if(!response.ok){const text=await response.text().catch(()=>"");throw new Error(text||`${message} (${response.status})`);}return response.json();}
export async function getAuthStatus():Promise<AuthStatus>{if(isTauriDesktop())return{required:false,authenticated:true};return json(await browserFetch(`${serverBaseUrl()}/api/auth/status`),'Could not check authentication');}
export async function login(password:string):Promise<void>{if(isTauriDesktop())return;const r=await browserFetch(`${serverBaseUrl()}/api/auth/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({password})});if(!r.ok)throw new Error(r.status===401?'Incorrect password':`Login failed (${r.status})`);}
export async function logout():Promise<void>{if(!isTauriDesktop())await browserFetch(`${serverBaseUrl()}/api/auth/logout`,{method:'POST'});}
export async function getSetupStatus():Promise<SetupStatus>{if(!isTauriDesktop())return{complete:true,users:await listUsers()};return invoke<SetupStatus>('setup_status');}
export async function completeSetup():Promise<void>{if(!isTauriDesktop())return;await invoke('complete_setup');}
export async function setIbroadcastClientId(clientId:string):Promise<void>{if(!isTauriDesktop())throw new Error('The iBroadcast app client ID is managed from the desktop server.');await invoke('set_ibroadcast_client_id',{clientId});}
export async function listUsers():Promise<UserProfile[]>{if(isTauriDesktop())return invoke<UserProfile[]>('list_users');return json(await browserFetch(`${serverBaseUrl()}/api/users`),'Could not load users');}
export async function createUser(name:string):Promise<UserProfile[]>{if(!isTauriDesktop())throw new Error('User management is available from the desktop server app.');return invoke<UserProfile[]>('create_user',{name});}
export async function renameUser(userId:string,name:string):Promise<UserProfile[]>{if(!isTauriDesktop())throw new Error('User management is available from the desktop server app.');return invoke<UserProfile[]>('rename_user',{userId,name});}
export async function deleteUser(userId:string):Promise<UserProfile[]>{if(!isTauriDesktop())throw new Error('User management is available from the desktop server app.');return invoke<UserProfile[]>('delete_user',{userId});}
export async function getUserPreferences():Promise<UserPreferences>{if(isTauriDesktop())return invoke<UserPreferences>('get_user_preferences',{userId:activeUserId});return json(await browserFetch(`${serverBaseUrl()}/api/preferences`),'Could not load preferences');}
export async function setUserTheme(theme:ThemeName):Promise<UserPreferences>{if(isTauriDesktop())return invoke<UserPreferences>('set_user_theme',{userId:activeUserId,theme});return json(await browserFetch(`${serverBaseUrl()}/api/preferences/theme`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({theme})}),'Could not save theme');}
export async function getAnalytics():Promise<AnalyticsSummary>{if(isTauriDesktop())return invoke<AnalyticsSummary>('user_analytics',{userId:activeUserId});return json(await browserFetch(`${serverBaseUrl()}/api/analytics`),'Could not load analytics');}
export async function listMedia(includeHidden=false):Promise<MediaItem[]>{if(isTauriDesktop())return invoke<MediaItem[]>('list_media',{userId:activeUserId,includeHidden});return json(await browserFetch(`${serverBaseUrl()}/api/library`),'Could not load media library');}
export async function getServerStatus():Promise<ServerStatus>{if(isTauriDesktop())return invoke<ServerStatus>('server_status');const status=await json<ServerStatus>(await browserFetch(`${serverBaseUrl()}/api/status`),'Could not reach media server');return{...status,localUrl:window.location.origin};}
export async function saveProgress(id:string,seconds:number,watchedSeconds=0):Promise<void>{if(isTauriDesktop()){await invoke('save_progress',{userId:activeUserId,id,seconds,watchedSeconds});return;}const r=await browserFetch(`${serverBaseUrl()}/api/progress/${encodeURIComponent(id)}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({seconds,watchedSeconds})});if(!r.ok)throw new Error(`Could not save playback progress (${r.status})`);}
export async function resetWatchStatus(ids:string[]):Promise<MediaItem[]>{if(isTauriDesktop())return invoke<MediaItem[]>('reset_watch_status',{userId:activeUserId,ids});return json(await browserFetch(`${serverBaseUrl()}/api/progress/reset`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({ids})}),'Could not reset watch status');}
export async function setHidden(targetType:'media'|'show',targetKey:string,hidden:boolean):Promise<MediaItem[]>{if(isTauriDesktop())return invoke<MediaItem[]>('set_hidden',{userId:activeUserId,targetType,targetKey,hidden});return json(await browserFetch(`${serverBaseUrl()}/api/hidden`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({targetType,targetKey,hidden})}),'Could not update hidden media');}
export async function listPlaylists():Promise<Playlist[]>{if(isTauriDesktop())return invoke<Playlist[]>('list_playlists',{userId:activeUserId});return json(await browserFetch(`${serverBaseUrl()}/api/playlists`),'Could not load playlists');}
export async function createPlaylist(name:string):Promise<Playlist[]>{if(isTauriDesktop())return invoke<Playlist[]>('create_playlist',{userId:activeUserId,name});return json(await browserFetch(`${serverBaseUrl()}/api/playlists`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name})}),'Could not create playlist');}
export async function addToPlaylist(playlistId:string,mediaId:string):Promise<Playlist[]>{if(isTauriDesktop())return invoke<Playlist[]>('add_to_playlist',{userId:activeUserId,playlistId,mediaId});return json(await browserFetch(`${serverBaseUrl()}/api/playlists/${encodeURIComponent(playlistId)}/add`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mediaId})}),'Could not add to playlist');}
export async function removeFromPlaylist(playlistId:string,mediaId:string):Promise<Playlist[]>{if(isTauriDesktop())return invoke<Playlist[]>('remove_from_playlist',{userId:activeUserId,playlistId,mediaId});return json(await browserFetch(`${serverBaseUrl()}/api/playlists/${encodeURIComponent(playlistId)}/remove`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mediaId})}),'Could not remove from playlist');}
export async function deletePlaylist(playlistId:string):Promise<Playlist[]>{if(isTauriDesktop())return invoke<Playlist[]>('delete_playlist',{userId:activeUserId,playlistId});return json(await browserFetch(`${serverBaseUrl()}/api/playlists/${encodeURIComponent(playlistId)}/delete`,{method:'POST'}),'Could not delete playlist');}
export async function rescanLibrary():Promise<void>{if(!isTauriDesktop())throw new Error('Library rescans are managed from the desktop server app.');await invoke('scan_library');}
export async function chooseLibraryPath():Promise<string|null>{if(!isTauriDesktop())return null;const{open}=await import('@tauri-apps/plugin-dialog');const selected=await open({directory:true,multiple:false});return typeof selected==='string'?selected:null;}
export async function setLibraryPath(path:string):Promise<void>{if(!isTauriDesktop())throw new Error('Library folders are managed from the desktop server app.');await invoke('set_library_path',{path});}
export async function setMoviePath(path:string):Promise<void>{if(!isTauriDesktop())throw new Error('Movie folders are managed from the desktop server app.');await invoke('set_movie_path',{path});}
export async function setTvPath(path:string):Promise<void>{if(!isTauriDesktop())throw new Error('TV folders are managed from the desktop server app.');await invoke('set_tv_path',{path});}
export async function setAccessPassword(password:string):Promise<void>{if(!isTauriDesktop())throw new Error('Access passwords are managed from the desktop server app.');await invoke('set_access_password',{password});}
export async function clearAccessPassword():Promise<void>{if(!isTauriDesktop())throw new Error('Access passwords are managed from the desktop server app.');await invoke('clear_access_password');}
export async function clearThumbnailCache():Promise<void>{if(!isTauriDesktop())throw new Error('Artwork cache is managed from the desktop server app.');await invoke('clear_thumbnail_cache');}
export async function identifyItem(id:string,identity:IdentityInput):Promise<MediaItem[]>{if(!isTauriDesktop())throw new Error('Identification corrections are managed from the desktop server app.');await invoke<MediaItem[]>('identify_item',{id,identity});return listMedia();}
export async function identifyShow(id:string,showTitle:string):Promise<MediaItem[]>{if(!isTauriDesktop())throw new Error('Identification corrections are managed from the desktop server app.');await invoke<MediaItem[]>('identify_show',{id,showTitle});return listMedia();}
export async function resetIdentification(id:string):Promise<MediaItem[]>{if(!isTauriDesktop())throw new Error('Identification corrections are managed from the desktop server app.');await invoke<MediaItem[]>('reset_identification',{id});return listMedia();}

export async function getIbroadcastStatus():Promise<IbConnectionStatus>{if(isTauriDesktop())return invoke<IbConnectionStatus>('ibroadcast_status',{userId:activeUserId});return json(await browserFetch(`${serverBaseUrl()}/api/ibroadcast/status`),'Could not check iBroadcast');}
export async function startIbroadcastDeviceAuth():Promise<IbDeviceCode>{if(isTauriDesktop())return invoke<IbDeviceCode>('ibroadcast_device_start');return json(await browserFetch(`${serverBaseUrl()}/api/ibroadcast/device/start`,{method:'POST'}),'Could not start iBroadcast authorization');}
export async function pollIbroadcastDeviceAuth(deviceCode:string):Promise<IbDevicePoll>{if(isTauriDesktop())return invoke<IbDevicePoll>('ibroadcast_device_poll',{userId:activeUserId,deviceCode});return json(await browserFetch(`${serverBaseUrl()}/api/ibroadcast/device/poll`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({deviceCode})}),'Could not finish iBroadcast authorization');}
export async function syncIbroadcast():Promise<IbLibrary>{if(isTauriDesktop())return invoke<IbLibrary>('ibroadcast_sync',{userId:activeUserId});return json(await browserFetch(`${serverBaseUrl()}/api/ibroadcast/sync`,{method:'POST'}),'Could not sync iBroadcast');}
export async function getIbroadcastLibrary():Promise<IbLibrary>{if(isTauriDesktop())return invoke<IbLibrary>('ibroadcast_library',{userId:activeUserId});return json(await browserFetch(`${serverBaseUrl()}/api/ibroadcast/library`),'Could not load iBroadcast library');}
export async function disconnectIbroadcast():Promise<void>{if(isTauriDesktop()){await invoke('ibroadcast_disconnect',{userId:activeUserId});return;}const r=await browserFetch(`${serverBaseUrl()}/api/ibroadcast/disconnect`,{method:'POST'});if(!r.ok)throw new Error('Could not disconnect iBroadcast');}
export const ibroadcastStreamUrl=(trackId:string)=>`${serverBaseUrl()}/api/ibroadcast/stream/${encodeURIComponent(trackId)}`;