import { startTransition, useEffect, useRef, useState } from "react";
import { resolveMediaUrl, saveProgress as persistProgress } from "../../../api";
import type { MediaItem } from "../../../types";
import type { CollectionSession } from "../../collections/hooks/useCollectionsController";

export function usePlaybackController({ items, setItems, selected, setSelected, sessions, markPlaying, markIdle, requestCollectionUnlock }: { items: MediaItem[]; setItems: React.Dispatch<React.SetStateAction<MediaItem[]>>; selected: MediaItem | null; setSelected: React.Dispatch<React.SetStateAction<MediaItem | null>>; sessions: Record<string, CollectionSession>; markPlaying: (item: MediaItem | null) => void; markIdle: (item: MediaItem | null) => void; requestCollectionUnlock: (sourceId: string) => void }) {
  const [pausedMedia, setPausedMedia] = useState<MediaItem | null>(null);
  const [subtitleChoice, setSubtitleChoice] = useState("off");
  const videoRef = useRef<HTMLVideoElement>(null);
  const lastProgressSaveRef = useRef(0);
  const lastWatchTickRef = useRef(Date.now());
  const sourceUrl = (() => { if (!selected) return ""; const url = resolveMediaUrl(selected.streamUrl); const token = selected.collectionSourceId ? sessions[selected.collectionSourceId]?.token : undefined; return url && token ? `${url}${url.includes("?") ? "&" : "?"}unlock=${encodeURIComponent(token)}` : url; })();
  const saveProgress = async (force = false) => { if (!selected || !videoRef.current) return; const current = Math.floor(videoRef.current.currentTime); if (!force && Math.abs(current - lastProgressSaveRef.current) < 15) return; const now = Date.now(); const elapsed = videoRef.current.paused ? 0 : Math.min(30, Math.max(0, Math.round((now - lastWatchTickRef.current) / 1000))); lastWatchTickRef.current = now; lastProgressSaveRef.current = current; try { await persistProgress(selected.id, current, elapsed); const stamp = Math.floor(Date.now() / 1000); setItems(existing => existing.map(item => item.id === selected.id ? { ...item, progressSeconds: current, lastWatchedAt: stamp } : item)); } catch { /* playback persistence is best effort */ } };
  const startPlayback = (item: MediaItem) => { if (item.collectionProtected && item.collectionSourceId && !sessions[item.collectionSourceId]) { requestCollectionUnlock(item.collectionSourceId); return; } let next = item; if (item.durationSeconds && item.progressSeconds > 0 && 1 - item.progressSeconds / item.durationSeconds <= .1) { const resume = window.confirm("Less than 10% remains.\n\nOK: continue where you left off\nCancel: restart from the beginning"); if (!resume) next = { ...item, progressSeconds: 0 }; } try { sessionStorage.setItem("onyx-current-media", JSON.stringify(next)); } catch { /* best effort */ } lastWatchTickRef.current = Date.now(); markPlaying(next); setPausedMedia(null); startTransition(() => setSelected(next)); setSubtitleChoice("off"); };
  const closePlayer = () => { void saveProgress(true); markIdle(selected); setSelected(null); setSubtitleChoice("off"); };
  const pauseForNavigation = () => { if (!selected) return; const current = Math.floor(videoRef.current?.currentTime ?? selected.progressSeconds); void saveProgress(true); videoRef.current?.pause(); markIdle(selected); setPausedMedia({ ...selected, progressSeconds: current }); startTransition(() => setSelected(null)); setSubtitleChoice("off"); };
  const resumePaused = () => { if (!pausedMedia) return; const latest = items.find(item => item.id === pausedMedia.id) ?? pausedMedia; lastWatchTickRef.current = Date.now(); setSelected({ ...latest, progressSeconds: pausedMedia.progressSeconds }); setPausedMedia(null); setSubtitleChoice("off"); };
  const changeSubtitle = (value: string) => { setSubtitleChoice(value); const video = videoRef.current; if (!video) return; for (let index = 0; index < video.textTracks.length; index++) video.textTracks[index].mode = value === String(index) ? "showing" : "disabled"; };
  useEffect(() => { const video = videoRef.current; if (!selected || !video) return; lastProgressSaveRef.current = selected.progressSeconds; lastWatchTickRef.current = Date.now(); const resume = () => { if (selected.progressSeconds > 5 && video.currentTime < 1) video.currentTime = selected.progressSeconds; }; video.addEventListener("loadedmetadata", resume); return () => video.removeEventListener("loadedmetadata", resume); }, [selected]);
  useEffect(() => { const reload = () => setSelected(current => current ? (items.find(item => item.id === current.id) ?? current) : current); window.addEventListener("onyx-subtitle-downloaded", reload); return () => window.removeEventListener("onyx-subtitle-downloaded", reload); }, [items]);
  return { selected, setSelected, pausedMedia, setPausedMedia, subtitleChoice, videoRef, sourceUrl, playableSubtitles: selected?.subtitles.filter(track => track.url) ?? [], startPlayback, closePlayer, pauseForNavigation, resumePaused, saveProgress, changeSubtitle };
}
