import { useEffect, useState } from 'react';
import { Check, LoaderCircle, Search, Star, X } from 'lucide-react';
import { applyMetadataMatch, searchMetadata, serverBaseUrl } from '../../../api';
import type { MediaItem, MetadataSearchResult } from '../../../types';

export function MetadataMatchDialog({item,onClose,onMatched}:{item:MediaItem;onClose:()=>void;onMatched:(items:MediaItem[])=>void}){
 const initial=item.kind==='episode'?(item.showTitle??item.title):item.title;
 const[query,setQuery]=useState(initial);const[results,setResults]=useState<MetadataSearchResult[]>([]);const[busy,setBusy]=useState(false);const[applying,setApplying]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);
 const search=async(value=query)=>{const clean=value.trim();if(!clean)return;setBusy(true);setError(null);try{setResults(await searchMetadata(item.id,clean))}catch(c){setError(String(c));setResults([])}finally{setBusy(false)}};
 useEffect(()=>{void search(initial)},[item.id]);
 const choose=async(result:MetadataSearchResult)=>{setApplying(`${result.entityType}:${result.providerId}`);setError(null);try{onMatched(await applyMetadataMatch(item.id,result.providerId,result.entityType));onClose()}catch(c){setError(String(c))}finally{setApplying(null)}};
 const poster=(url?:string)=>{if(!url)return undefined;try{const parsed=new URL(url);if(parsed.hostname==='image.tmdb.org'){const parts=parsed.pathname.split('/');const size=parts[3]||'w342';const path='/'+parts.slice(4).join('/');return `${serverBaseUrl()}/api/metadata/image/${size}/${encodeURIComponent(path)}`}}catch{}return url};
 const targetLabel=item.kind==='episode'?'TV series':item.kind==='special'?'movie or TV series':'movie';
 const placeholder=item.kind==='special'?'Search title, TMDB ID/URL, or IMDb ID':`Search ${item.kind==='episode'?'TV shows':'movies'}`;
 return <div className="match-overlay" role="dialog" aria-modal="true" aria-label="Fix metadata match" onClick={onClose}><section className="match-dialog" onClick={e=>e.stopPropagation()}><header><div><p className="eyebrow">FIX MATCH</p><h2>{item.kind==='episode'?(item.showTitle??item.title):item.title}</h2><p>Choose the real {targetLabel}. Specials search both TMDB catalogues and remain in Specials even when enriched from a TV series. You can also enter a TMDB ID, typed reference such as tmdb:tv:99984, a TMDB URL, or an IMDb ID.</p></div><button className="icon-action" aria-label="Close" onClick={onClose}><X size={18}/></button></header><form className="match-search" onSubmit={e=>{e.preventDefault();void search()}}><Search size={18}/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder={placeholder}/><button type="submit" disabled={busy}>{busy?<LoaderCircle className="spin" size={17}/>:<Search size={17}/>}Search</button></form>{error&&<div className="error-banner">{error}</div>}<div className="match-results">{!busy&&results.length===0&&!error&&<div className="match-empty"><Search size={32}/><strong>No results</strong><p>Try a shorter title or paste a TMDB/IMDb identifier.</p></div>}{results.map(result=>{const applyingKey=`${result.entityType}:${result.providerId}`;return <article className="match-result" key={`${result.provider}:${result.entityType}:${result.providerId}`}><div className="match-poster">{result.posterUrl?<img src={poster(result.posterUrl)} alt={`${result.title} poster`} loading="lazy"/>:<span>{result.title.charAt(0)}</span>}</div><div className="match-copy"><div className="match-result-heading"><h3>{result.title}</h3><span>{result.entityType==='series'?'TV Series':'Movie'}</span>{result.year&&<span>{result.year}</span>}{result.rating!=null&&<span className="match-rating"><Star size={13} fill="currentColor"/>{result.rating.toFixed(1)}</span>}</div><p>{result.overview||'No description available.'}</p><small>{result.provider.toUpperCase()} {result.entityType==='series'?'TV':'MOVIE'} #{result.providerId}</small></div><button className="primary match-use" disabled={Boolean(applying)} onClick={()=>void choose(result)}>{applying===applyingKey?<LoaderCircle className="spin" size={17}/>:<Check size={17}/>}Use this match</button></article>})}</div><footer><span>This product uses the TMDB API but is not endorsed or certified by TMDB.</span><button onClick={onClose}>Cancel</button></footer></section></div>;
}
