pub mod tmdb;

use crate::models::{AnalyticsEntry, MediaItem, MetadataEntity, ProviderMatch};
use rusqlite::{params, Connection, OptionalExtension};
use sha2::{Digest, Sha256};
use std::{collections::{BTreeMap, HashMap}, path::Path};

fn stable_id(prefix:&str,key:&str)->String{let mut h=Sha256::new();h.update(format!("{prefix}:{key}").as_bytes());format!("{prefix}-{}",&hex::encode(h.finalize())[..20])}
fn norm(value:&str)->String{value.trim().to_lowercase().split_whitespace().collect::<Vec<_>>().join(" ")}
fn art_url(size:&str,path:&str)->String{format!("/api/metadata/image/{size}/{}",urlencoding::encode(path))}

pub fn init(path:&Path)->Result<(),String>{let conn=Connection::open(path).map_err(|e|e.to_string())?;conn.execute_batch("CREATE TABLE IF NOT EXISTS metadata_entities(id TEXT PRIMARY KEY,entity_type TEXT NOT NULL,parent_id TEXT,title TEXT NOT NULL,original_title TEXT,year INTEGER,overview TEXT,release_date TEXT,runtime_minutes INTEGER,season_number INTEGER,episode_number INTEGER,genres_json TEXT NOT NULL DEFAULT '[]',rating REAL,poster_path TEXT,backdrop_path TEXT,still_path TEXT,metadata_json TEXT NOT NULL DEFAULT '{}',updated_at INTEGER NOT NULL DEFAULT(unixepoch()));CREATE TABLE IF NOT EXISTS provider_matches(entity_id TEXT NOT NULL,provider TEXT NOT NULL,provider_id TEXT NOT NULL,matched_by TEXT NOT NULL DEFAULT 'automatic',confidence REAL,locked INTEGER NOT NULL DEFAULT 0,updated_at INTEGER NOT NULL DEFAULT(unixepoch()),PRIMARY KEY(entity_id,provider),FOREIGN KEY(entity_id) REFERENCES metadata_entities(id) ON DELETE CASCADE);CREATE TABLE IF NOT EXISTS media_entity_links(media_id TEXT PRIMARY KEY,entity_id TEXT NOT NULL,FOREIGN KEY(entity_id) REFERENCES metadata_entities(id) ON DELETE CASCADE);CREATE INDEX IF NOT EXISTS idx_metadata_parent ON metadata_entities(parent_id,entity_type,season_number,episode_number);CREATE INDEX IF NOT EXISTS idx_provider_match ON provider_matches(provider,provider_id);").map_err(|e|e.to_string())?;Ok(())}
fn upsert_entity(conn:&Connection,e:&MetadataEntity)->Result<(),String>{let genres=serde_json::to_string(&e.genres).map_err(|x|x.to_string())?;let raw=e.metadata_json.to_string();conn.execute("INSERT INTO metadata_entities(id,entity_type,parent_id,title,original_title,year,overview,release_date,runtime_minutes,season_number,episode_number,genres_json,rating,poster_path,backdrop_path,still_path,metadata_json,updated_at)VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12,?13,?14,?15,?16,?17,unixepoch()) ON CONFLICT(id)DO UPDATE SET entity_type=excluded.entity_type,parent_id=excluded.parent_id,title=CASE WHEN metadata_entities.title='' THEN excluded.title ELSE metadata_entities.title END,year=COALESCE(metadata_entities.year,excluded.year),season_number=COALESCE(metadata_entities.season_number,excluded.season_number),episode_number=COALESCE(metadata_entities.episode_number,excluded.episode_number),updated_at=unixepoch()",params![e.id,e.entity_type,e.parent_id,e.title,e.original_title,e.year,e.overview,e.release_date,e.runtime_minutes,e.season_number,e.episode_number,genres,e.rating,e.poster_path,e.backdrop_path,e.still_path,raw]).map_err(|x|x.to_string())?;Ok(())}
fn provider_backed_link(conn:&Connection,media_id:&str)->Result<bool,String>{let found:i64=conn.query_row("WITH RECURSIVE ancestors(id,parent_id) AS (SELECT e.id,e.parent_id FROM metadata_entities e JOIN media_entity_links l ON l.entity_id=e.id WHERE l.media_id=?1 UNION ALL SELECT p.id,p.parent_id FROM metadata_entities p JOIN ancestors a ON p.id=a.parent_id) SELECT EXISTS(SELECT 1 FROM provider_matches pm WHERE pm.entity_id IN(SELECT id FROM ancestors))",[media_id],|r|r.get(0)).map_err(|e|e.to_string())?;Ok(found!=0)}
fn linked_series_id(conn:&Connection,media_id:&str)->Result<Option<String>,String>{conn.query_row("WITH RECURSIVE ancestors(id,parent_id,entity_type) AS (SELECT e.id,e.parent_id,e.entity_type FROM metadata_entities e JOIN media_entity_links l ON l.entity_id=e.id WHERE l.media_id=?1 UNION ALL SELECT p.id,p.parent_id,p.entity_type FROM metadata_entities p JOIN ancestors a ON p.id=a.parent_id) SELECT id FROM ancestors WHERE entity_type='series' LIMIT 1",[media_id],|r|r.get::<_,String>(0)).optional().map_err(|e|e.to_string())}
fn preserve_or_link(conn:&Connection,media_id:&str,entity_id:&str)->Result<(),String>{if provider_backed_link(conn,media_id)?{return Ok(())}conn.execute("INSERT INTO media_entity_links(media_id,entity_id)VALUES(?1,?2)ON CONFLICT(media_id)DO UPDATE SET entity_id=excluded.entity_id",params![media_id,entity_id]).map_err(|e|e.to_string())?;Ok(())}
fn preserve_series_or_relink_episode(conn:&Connection,media_id:&str,series_id:&str,episode_id:&str)->Result<(),String>{if provider_backed_link(conn,media_id)?{if linked_series_id(conn,media_id)?.as_deref()!=Some(series_id){return Ok(())}}conn.execute("INSERT INTO media_entity_links(media_id,entity_id)VALUES(?1,?2)ON CONFLICT(media_id)DO UPDATE SET entity_id=excluded.entity_id",params![media_id,episode_id]).map_err(|e|e.to_string())?;Ok(())}
pub fn reconcile_local_entities(path:&Path,items:&[MediaItem])->Result<(),String>{let mut conn=Connection::open(path).map_err(|e|e.to_string())?;let tx=conn.transaction().map_err(|e|e.to_string())?;for item in items{if item.kind=="movie"{let entity_id=stable_id("movie",&item.id);let e=MetadataEntity{id:entity_id.clone(),entity_type:"movie".into(),parent_id:None,title:item.title.clone(),original_title:None,year:item.year,overview:None,release_date:None,runtime_minutes:item.duration_seconds.map(|v|(v/60)as u32),season_number:None,episode_number:None,genres:vec![],rating:None,poster_path:None,backdrop_path:None,still_path:None,metadata_json:serde_json::json!({"localMediaId":item.id})};upsert_entity(&tx,&e)?;preserve_or_link(&tx,&item.id,&entity_id)?;}else{let show=item.show_title.clone().unwrap_or_else(||"TV".into());let series_id=stable_id("series",&norm(&show));let series=MetadataEntity{id:series_id.clone(),entity_type:"series".into(),parent_id:None,title:show.clone(),original_title:None,year:item.year,overview:None,release_date:None,runtime_minutes:None,season_number:None,episode_number:None,genres:vec![],rating:None,poster_path:None,backdrop_path:None,still_path:None,metadata_json:serde_json::json!({"localShowTitle":show})};upsert_entity(&tx,&series)?;let season_no=item.season.unwrap_or(0);let season_id=stable_id("season",&format!("{series_id}:{season_no}"));let season=MetadataEntity{id:season_id.clone(),entity_type:"season".into(),parent_id:Some(series_id.clone()),title:if season_no==0{"Specials".into()}else{format!("Season {season_no}")},original_title:None,year:None,overview:None,release_date:None,runtime_minutes:None,season_number:Some(season_no),episode_number:None,genres:vec![],rating:None,poster_path:None,backdrop_path:None,still_path:None,metadata_json:serde_json::json!({})};upsert_entity(&tx,&season)?;let ep_no=item.episode.unwrap_or(0);let episode_id=stable_id("episode",&format!("{series_id}:{season_no}:{ep_no}:{}",item.episode_end.unwrap_or(ep_no)));let episode=MetadataEntity{id:episode_id.clone(),entity_type:"episode".into(),parent_id:Some(season_id),title:item.title.clone(),original_title:None,year:item.year,overview:None,release_date:None,runtime_minutes:item.duration_seconds.map(|v|(v/60)as u32),season_number:Some(season_no),episode_number:Some(ep_no),genres:vec![],rating:None,poster_path:None,backdrop_path:None,still_path:None,metadata_json:serde_json::json!({"localMediaId":item.id})};upsert_entity(&tx,&episode)?;preserve_series_or_relink_episode(&tx,&item.id,&series_id,&episode_id)?;}}tx.commit().map_err(|e|e.to_string())}
fn row_entity(row:&rusqlite::Row<'_>)->rusqlite::Result<MetadataEntity>{let genres:String=row.get(11)?;let raw:String=row.get(16)?;Ok(MetadataEntity{id:row.get(0)?,entity_type:row.get(1)?,parent_id:row.get(2)?,title:row.get(3)?,original_title:row.get(4)?,year:row.get(5)?,overview:row.get(6)?,release_date:row.get(7)?,runtime_minutes:row.get(8)?,season_number:row.get(9)?,episode_number:row.get(10)?,genres:serde_json::from_str(&genres).unwrap_or_default(),rating:row.get(12)?,poster_path:row.get(13)?,backdrop_path:row.get(14)?,still_path:row.get(15)?,metadata_json:serde_json::from_str(&raw).unwrap_or_else(|_|serde_json::json!({}))})}
const ENTITY_SELECT:&str="SELECT id,entity_type,parent_id,title,original_title,year,overview,release_date,runtime_minutes,season_number,episode_number,genres_json,rating,poster_path,backdrop_path,still_path,metadata_json FROM metadata_entities";
pub fn entity_for_media(path:&Path,media_id:&str)->Result<Option<MetadataEntity>,String>{let conn=Connection::open(path).map_err(|e|e.to_string())?;let sql=format!("{ENTITY_SELECT} WHERE id=(SELECT entity_id FROM media_entity_links WHERE media_id=?1)");conn.query_row(&sql,[media_id],row_entity).optional().map_err(|e|e.to_string())}
pub fn series_for_media(path:&Path,media_id:&str)->Result<Option<MetadataEntity>,String>{let Some(entity)=entity_for_media(path,media_id)? else{return Ok(None)};if entity.entity_type=="movie"||entity.entity_type=="series"{return Ok(Some(entity))}let conn=Connection::open(path).map_err(|e|e.to_string())?;let sql=format!("WITH RECURSIVE ancestors(id,parent_id) AS (SELECT id,parent_id FROM metadata_entities WHERE id=?1 UNION ALL SELECT m.id,m.parent_id FROM metadata_entities m JOIN ancestors a ON m.id=a.parent_id) {ENTITY_SELECT} WHERE id IN(SELECT id FROM ancestors) AND entity_type='series' LIMIT 1");conn.query_row(&sql,[entity.id],row_entity).optional().map_err(|e|e.to_string())}
pub fn children(path:&Path,parent_id:&str,kind:&str)->Result<Vec<MetadataEntity>,String>{let conn=Connection::open(path).map_err(|e|e.to_string())?;let sql=format!("{ENTITY_SELECT} WHERE parent_id=?1 AND entity_type=?2 ORDER BY COALESCE(season_number,0),COALESCE(episode_number,0),title");let mut stmt=conn.prepare(&sql).map_err(|e|e.to_string())?;let rows=stmt.query_map(params![parent_id,kind],row_entity).map_err(|e|e.to_string())?;let mut out=vec![];for row in rows{out.push(row.map_err(|e|e.to_string())?)}Ok(out)}
pub fn set_provider_match(path:&Path,m:&ProviderMatch)->Result<(),String>{Connection::open(path).map_err(|e|e.to_string())?.execute("INSERT INTO provider_matches(entity_id,provider,provider_id,matched_by,confidence,locked,updated_at)VALUES(?1,?2,?3,?4,?5,?6,unixepoch()) ON CONFLICT(entity_id,provider)DO UPDATE SET provider_id=excluded.provider_id,matched_by=excluded.matched_by,confidence=excluded.confidence,locked=excluded.locked,updated_at=unixepoch()",params![m.entity_id,m.provider,m.provider_id,m.matched_by,m.confidence,if m.locked{1}else{0}]).map_err(|e|e.to_string())?;Ok(())}
pub fn provider_match(path:&Path,entity_id:&str,provider:&str)->Result<Option<ProviderMatch>,String>{let conn=Connection::open(path).map_err(|e|e.to_string())?;conn.query_row("SELECT entity_id,provider,provider_id,matched_by,confidence,locked FROM provider_matches WHERE entity_id=?1 AND provider=?2",params![entity_id,provider],|r|Ok(ProviderMatch{entity_id:r.get(0)?,provider:r.get(1)?,provider_id:r.get(2)?,matched_by:r.get(3)?,confidence:r.get(4)?,locked:r.get::<_,i64>(5)?!=0})).optional().map_err(|e|e.to_string())}
pub fn clear_provider_match(path:&Path,entity_id:&str,provider:&str)->Result<(),String>{Connection::open(path).map_err(|e|e.to_string())?.execute("DELETE FROM provider_matches WHERE entity_id=?1 AND provider=?2",params![entity_id,provider]).map_err(|e|e.to_string())?;Ok(())}
pub fn replace_entity_metadata(path:&Path,e:&MetadataEntity)->Result<(),String>{let conn=Connection::open(path).map_err(|e|e.to_string())?;let genres=serde_json::to_string(&e.genres).map_err(|x|x.to_string())?;conn.execute("UPDATE metadata_entities SET title=?2,original_title=?3,year=?4,overview=?5,release_date=?6,runtime_minutes=?7,genres_json=?8,rating=?9,poster_path=?10,backdrop_path=?11,still_path=?12,metadata_json=?13,updated_at=unixepoch() WHERE id=?1",params![e.id,e.title,e.original_title,e.year,e.overview,e.release_date,e.runtime_minutes,genres,e.rating,e.poster_path,e.backdrop_path,e.still_path,e.metadata_json.to_string()]).map_err(|x|x.to_string())?;Ok(())}
pub fn enrich_media(path:&Path,items:&mut[MediaItem])->Result<(),String>{let conn=Connection::open(path).map_err(|e|e.to_string())?;let sql=format!("{ENTITY_SELECT} WHERE id=(SELECT entity_id FROM media_entity_links WHERE media_id=?1)");for item in items.iter_mut(){let mut direct:Option<MetadataEntity>=None;if let Ok(entity)=conn.query_row(&sql,[&item.id],row_entity){item.metadata_entity_id=Some(entity.id.clone());item.overview=entity.overview.clone();item.genres=entity.genres.clone();item.rating=entity.rating;item.release_date=entity.release_date.clone();if let Some(p)=entity.poster_path.as_deref(){item.poster_url=Some(art_url("w500",p));}if let Some(p)=entity.backdrop_path.as_deref(){item.backdrop_url=Some(art_url("w1280",p));}if let Some(p)=entity.still_path.as_deref(){item.thumbnail_url=Some(art_url("w500",p));}if let Some(m)=provider_match(path,&entity.id,"tmdb")?{item.provider=Some(m.provider);item.provider_id=Some(m.provider_id);}direct=Some(entity);}if item.kind=="episode"{if let Some(series)=series_for_media(path,&item.id)?{if item.genres.is_empty(){item.genres=series.genres.clone()}if item.provider_id.is_none(){if let Some(m)=provider_match(path,&series.id,"tmdb")?{item.provider=Some(m.provider);item.provider_id=Some(m.provider_id);}}if direct.as_ref().and_then(|e|e.overview.as_ref()).is_none(){item.overview=direct.as_ref().and_then(|e|e.overview.clone()).or(series.overview.clone())}if direct.as_ref().and_then(|e|e.poster_path.as_ref()).is_none(){if let Some(p)=series.poster_path.as_deref(){item.poster_url=Some(art_url("w500",p));}}if direct.as_ref().and_then(|e|e.backdrop_path.as_ref()).is_none(){if let Some(p)=series.backdrop_path.as_deref(){item.backdrop_url=Some(art_url("w1280",p));}}}}}Ok(())}
pub fn genre_watch_totals(path:&Path,user_id:&str)->Result<Vec<AnalyticsEntry>,String>{let conn=Connection::open(path).map_err(|e|e.to_string())?;let mut stmt=conn.prepare("SELECT COALESCE(CASE WHEN me.genres_json='[]' AND me.entity_type='episode' THEN series.genres_json ELSE me.genres_json END,'[]'),uw.seconds FROM user_watch_time uw JOIN media_entity_links l ON l.media_id=uw.media_id JOIN metadata_entities me ON me.id=l.entity_id LEFT JOIN metadata_entities season ON season.id=me.parent_id LEFT JOIN metadata_entities series ON series.id=season.parent_id WHERE uw.user_id=?1 AND uw.seconds>0").map_err(|e|e.to_string())?;let rows=stmt.query_map([user_id],|r|Ok((r.get::<_,String>(0)?,r.get::<_,u64>(1)?))).map_err(|e|e.to_string())?;let mut totals:BTreeMap<String,u64>=BTreeMap::new();for row in rows{let(g,s)=row.map_err(|e|e.to_string())?;let genres:Vec<String>=serde_json::from_str(&g).unwrap_or_default();for genre in genres{*totals.entry(genre).or_default()+=s;}}let mut out=totals.into_iter().map(|(label,seconds)|AnalyticsEntry{label,seconds}).collect::<Vec<_>>();out.sort_by(|a,b|b.seconds.cmp(&a.seconds));Ok(out)}
pub fn series_local_seasons(path:&Path,series_id:&str)->Result<HashMap<u16,Vec<MetadataEntity>>,String>{let seasons=children(path,series_id,"season")?;let mut out=HashMap::new();for season in seasons{let n=season.season_number.unwrap_or(0);out.insert(n,children(path,&season.id,"episode")?);}Ok(out)}
