import { useEffect,useState } from 'react';
import { FolderOpen,Lock,Plus,Save,Trash2,X } from 'lucide-react';
import { chooseCollectionFolder,deleteCollectionSource,listCollectionSources,saveCollectionSource } from '../../../api';
import type { CollectionSource } from '../../../types';

export function CollectionSourcesSettings({onChanged}:{onChanged?:()=>void|Promise<void>}){
 const[sources,setSources]=useState<CollectionSource[]>([]);const[editing,setEditing]=useState<CollectionSource>();const[name,setName]=useState('Collections');const[path,setPath]=useState('');const[protectedSource,setProtected]=useState(false);const[pin,setPin]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState<string>();
 useEffect(()=>{void listCollectionSources().then(setSources).catch(c=>setError(String(c)))},[]);
 const reset=()=>{setEditing(undefined);setName('Collections');setPath('');setProtected(false);setPin('')};
 const edit=(source:CollectionSource)=>{setEditing(source);setName(source.name);setPath(source.path);setProtected(source.protected);setPin('')};
 const choose=async()=>{const selected=await chooseCollectionFolder();if(selected)setPath(selected)};
 const save=async()=>{if(!name.trim()||!path)return;setBusy(true);setError(undefined);try{setSources(await saveCollectionSource({id:editing?.id,name:name.trim(),path,protected:protectedSource,pin:pin||undefined}));reset();await onChanged?.()}catch(c){setError(String(c))}finally{setBusy(false)}};
 const remove=async(source:CollectionSource)=>{if(!confirm(`Remove “${source.name}” from Onyx? The video files will not be deleted.`))return;setBusy(true);try{setSources(await deleteCollectionSource(source.id));await onChanged?.()}catch(c){setError(String(c))}finally{setBusy(false)}};
 return <div className="collection-source-settings"><div className="settings-card collection-source-intro"><div><h3>Collections</h3><p>Add folders for home videos, clips, archives, or anything that does not belong under Movies, TV, or Specials. Each source receives its own sidebar entry and is grouped by subfolder.</p></div><Lock size={24}/></div>{error&&<div className="error-banner">{error}</div>}<div className="settings-card collection-source-builder"><h3>{editing?'Edit video source':'Add video source'}</h3><label className="setup-field"><span>Sidebar name</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="Collections"/></label><label className="setup-field"><span>Video folder</span><div className="caption-path-row"><input value={path} readOnly placeholder="Choose a folder"/><button onClick={()=>void choose()}><FolderOpen size={16}/>Choose</button></div></label><label className="settings-check"><input type="checkbox" checked={protectedSource} onChange={e=>setProtected(e.target.checked)}/><span>Require a PIN to open this source</span></label>{protectedSource&&<label className="setup-field"><span>{editing&&editing.protected?'New PIN (leave empty to keep current PIN)':'PIN — 4 to 12 numbers'}</span><input type="password" inputMode="numeric" pattern="[0-9]*" maxLength={12} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,''))}/></label>}<div className="metadata-actions"><button className="primary" disabled={busy||!name.trim()||!path||(protectedSource&&!editing?.protected&&pin.length<4)} onClick={()=>void save()}><Save size={16}/>{busy?'Scanning…':editing?'Save source':'Add and scan source'}</button>{editing&&<button onClick={reset}><X size={16}/>Cancel</button>}</div></div><div className="collection-source-list">{sources.map(source=><article className="settings-card" key={source.id}><div><h3>{source.name}</h3><p title={source.path}>{source.path}</p>{source.protected&&<small><Lock size={13}/>PIN protected · relocks after 30 idle minutes</small>}</div><button onClick={()=>edit(source)}>Edit</button><button className="danger-text" disabled={busy} onClick={()=>void remove(source)}><Trash2 size={15}/>Remove</button></article>)}</div>{!sources.length&&<p className="muted"><Plus size={14}/> No collection sources configured yet.</p>}</div>
}
